Repository privacyguides/privacyguides.org, pull requests merged in 2021-11, with the labels that each got.

#225 Add monero note (ivpn)
  _includes/legacy/sections/vpn.html
Labels: providers

#96 Minor update to app description
  _includes/legacy/sections/file-encryption.html
Labels: software, correction

#255 Remove encrypted DNS recommendation
  legacy_pages/providers/vpn.html
Labels: providers

#253 Remove Ubuntu touch
  _includes/legacy/sections/other-mobile-operating-systems.html
  legacy_pages/os.html
Labels: os

#254 Remove hosting providers
  _data/nav/2_providers.yml
  _includes/legacy/sections/cloud-storage.html
  _includes/legacy/sections/hosting-provider.html
  collections/_posts/2019-08-22-self-hosting-shadowsocks-vpn-outline.md
  legacy_pages/providers.html
  legacy_pages/providers/hosting.html
Labels: providers

#258 Remove 7zip
  _includes/legacy/sections/file-encryption.html
  assets/img/legacy_svg/3rd-party/7zip.svg
Labels: software

#260 Remove Decentraleyes
  _includes/legacy/sections/browser-addons.html
  assets/img/legacy_svg/3rd-party/decentraleyes.svg
Labels: browsers

#262 Remove https everywhere
  _includes/legacy/sections/browser-addons.html
  assets/img/legacy_svg/3rd-party/https_everywhere.svg
Labels: browsers

#259 Remove canvas blocker
  _includes/legacy/sections/browser-addons.html
  assets/img/legacy_svg/3rd-party/canvasblocker.svg
Labels: browsers

#257 Revamping the VPN recommendations
  _includes/legacy/sections/vpn.html
  legacy_pages/providers/vpn.html
Labels: providers

#157 updated masterpassword to its new name: spectre.app
  _includes/legacy/sections/password-managers.html
Labels: software

#60 Remove Etag Stoppa
  _includes/legacy/sections/browser-addons.html
Labels: browsers, correction

#135 Extension links for Microsoft Edge updated and added
  _includes/legacy/sections/browser-addons.html
Labels: browsers

#153 Small fixes on VPN page
  legacy_pages/providers/vpn.html
Labels: providers

#283 Added a warning to Fruux: proprietary application
  _includes/legacy/sections/calendar-contacts-sync.html
Labels: providers

#285 Update Android recommendations
  _includes/legacy/sections/android-operating-systems.html
  assets/img/legacy_png/3rd-party/divestos.png
  assets/img/legacy_svg/3rd-party/bahnhof-dark.svg
  assets/img/legacy_svg/3rd-party/bahnhof.svg
  assets/img/legacy_svg/3rd-party/lineageos.svg
  assets/img/legacy_svg/3rd-party/njalla-dark.svg
  assets/img/legacy_svg/3rd-party/njalla.svg
Labels: os, hardware

#333 Convert Cloud Storage from legacy
  _data/nav/2_providers.yml
  _data/providers/cloud/1_nextcloud.yml
  _data/providers/cloud/2_proton-drive.yml
  _data/providers/cloud/3_tahoe-lafs.yml
  _includes/legacy/sections/calendar-contacts-sync.html
  _includes/legacy/sections/cloud.html
  assets/img/cloud/nextcloud.svg
  assets/img/cloud/protondrive.svg
  assets/img/cloud/tahoe-lafs-dark.svg
  assets/img/cloud/tahoe-lafs.svg
  collections/_evergreen/cloud.html
  legacy_pages/providers/cloud.html
Labels: providers, software, legacy migration

#274 Video frontend Revamp
  _data/nav/2_providers.yml
  _data/nav/3_software.yml
  _data/software/video-streaming/1_freetube.yml
  _data/software/video-streaming/2_lbry.yml
  _data/software/video-streaming/3_newpipe.yml
  _includes/legacy/sections/decentralized-video.html
  _includes/legacy/sections/video-frontends.html
  assets/img/legacy_svg/3rd-party/invidious.svg
  assets/img/legacy_svg/3rd-party/peertube.svg
  assets/img/video-streaming/freetube.png
  assets/img/video-streaming/lbry.svg
  assets/img/video-streaming/newpipe.svg
  collections/_evergreen/video-streaming.html
  legacy_pages/providers/video.html
  legacy_pages/software.html
Labels: providers

#337 Re-add privacy_policy functionality
  _includes/recommendation-card.html
Labels: bug

#384 Remove LibreCMC
  _includes/legacy/sections/router-firmware.html
  assets/img/legacy_svg/3rd-party/librecmc-dark.svg
  assets/img/legacy_svg/3rd-party/librecmc.svg
Labels: os, approved

#342 Search engines revamp
  _data/nav/2_providers.yml
  _data/providers/search-engines/1_duckduckgo.yml
  _data/providers/search-engines/2_startpage.yml
  _data/providers/search-engines/3_mojeek.yml
  _data/providers/search-engines/4_searx.yml
  _includes/legacy/sections/search-engines.html
  assets/img/legacy_svg/3rd-party/startpage.svg
  assets/img/search-engines/duckduckgo.svg
  assets/img/search-engines/mojeek.svg
  assets/img/search-engines/searx.svg
  assets/img/search-engines/startpage.svg
  collections/_evergreen/search-engines.html
  legacy_pages/providers.html
  legacy_pages/providers/search-engines.html
Labels: providers, approved, legacy migration

#392 Add non Javascript frontends for video streaming
  _data/software/video-streaming-clients/1_freetube.yml
  _data/software/video-streaming-clients/2_lbry.yml
  _data/software/video-streaming-clients/3_newpipe.yml
  _data/software/video-streaming-front-ends/1_invidious.yml
  _data/software/video-streaming/1_freetube.yml
  _data/software/video-streaming/2_lbry.yml
  _data/software/video-streaming/3_newpipe.yml
  assets/img/video-streaming/freetube.png
  assets/img/video-streaming/freetube.svg
  assets/img/video-streaming/invidious-dark.svg
  assets/img/video-streaming/invidious.svg
  assets/img/video-streaming/lbry.svg
  assets/img/video-streaming/newpipe.svg
  collections/_evergreen/video-streaming.html
Labels: providers, approved, legacy migration
