Repository privacyguides/privacyguides.org, pull requests merged in 2022-09, with the labels that each got.

#1705 Grammar fixes on the 1Password card
  docs/passwords.en.md
Labels: t:correction

#1731 Remove custom theme icons
  Pipfile.lock
  docs/advanced/integrating-metadata-removal.en.md
  docs/advanced/signal-configuration-hardening.en.md
  docs/android.en.md
  docs/android/overview.en.md
  docs/assets/stylesheets/extra.css
  docs/basics/common-threats.en.md
  docs/basics/threat-modeling.en.md
  docs/basics/tor-overview.md
  docs/calendar-contacts.en.md
  docs/cloud.en.md
  docs/data-redaction.en.md
  docs/desktop-browsers.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/encryption.en.md
  docs/file-sharing.en.md
  docs/index.en.md
  docs/linux-desktop.en.md
  docs/linux-desktop/overview.en.md
  docs/mobile-browsers.en.md
  docs/multi-factor-authentication.en.md
  docs/news-aggregators.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/productivity.en.md
  docs/qubes.en.md
  docs/real-time-communication.en.md
  docs/search-engines.en.md
  docs/self-contained-networks.en.md
  docs/tools.en.md
  docs/video-streaming.en.md
  docs/vpn.en.md
  mkdocs.production.yml
  mkdocs.yml
  theme/.icons/hero/LICENSE.txt
  theme/.icons/hero/arrow-circle-right-fill.svg
  theme/.icons/hero/emoji-happy.svg
  theme/.icons/hero/emoji-sad.svg
  theme/.icons/hero/moon.svg
  theme/.icons/hero/sparkles.svg
  theme/.icons/hero/sun.svg
  theme/.icons/pg/f-droid.svg
  theme/.icons/pg/flathub.svg
  theme/.icons/pg/i2p.svg
  theme/.icons/pg/ios.svg
  theme/.icons/pg/linux.svg
  theme/.icons/pg/macos.svg
  theme/.icons/pg/matrix.svg
  theme/.icons/pg/mix.svg
  theme/.icons/pg/netbsd.svg
  theme/.icons/pg/openbsd.svg
  theme/.icons/pg/qubes-os.svg
  theme/.icons/pg/sailfish-os.svg
  theme/.icons/pg/textformat-size.svg
  theme/.icons/pg/tor.svg
Labels: c:enhancements

#1755 Disable HTML Minification
  Pipfile
  Pipfile.lock
  mkdocs.production.yml
Labels: t:bug, fix:python

#1757 Improve Android introduction
  docs/android.en.md
  docs/assets/stylesheets/extra.css
Labels: c:os

#1756 Remove I2P and Freenet
  docs/advanced/signal-configuration-hardening.en.md
  docs/android.en.md
  docs/assets/img/self-contained-networks/freenet.svg
  docs/assets/img/self-contained-networks/i2p-dark.svg
  docs/assets/img/self-contained-networks/i2p.svg
  docs/basics/tor-overview.en.md
  docs/basics/vpn-overview.en.md
  docs/calendar-contacts.en.md
  docs/desktop-browsers.en.md
  docs/email.en.md
  docs/file-sharing.en.md
  docs/mobile-browsers.en.md
  docs/news-aggregators.en.md
  docs/qubes.en.md
  docs/real-time-communication.en.md
  docs/search-engines.en.md
  docs/self-contained-networks.en.md
  docs/tools.en.md
  docs/tor.en.md
  docs/vpn.en.md
  includes/abbreviations.en.md
  mkdocs.yml
Labels: c:browsers, c:software

#1768 Change GrapheneOS/CalyxOS comparison page name
  docs/android/grapheneos-vs-calyxos.en.md
Labels: c:guides

#1771 Small VPN Criteria cleanup
  docs/vpn.en.md
Labels: t:correction

#1772 Fix Diceware Links
  docs/basics/passwords-overview.en.md
Labels: t:correction

#1782 Fix broken internal links
  docs/android/grapheneos-vs-calyxos.en.md
  docs/basics/account-deletion.en.md
  docs/basics/email-security.en.md
  docs/basics/multi-factor-authentication.en.md
  docs/blog/2021/12/01/firefox-privacy-2021-update.md
  docs/email-clients.en.md
  docs/notebooks.en.md
  docs/real-time-communication/communication-network-types.md
  docs/real-time-communication/signal-configuration-hardening.en.md
Labels: c:blog, t:correction

#1815 Notebooks Page Cleanup
  docs/notebooks.en.md
Labels: t:correction

#1819 Writing review of threat-modeling.en.md
  docs/basics/threat-modeling.en.md
Labels: t:correction

#1817 Writing review of index.en.md
  docs/index.en.md
Labels: t:correction
