Repository privacyguides/privacyguides.org, pull requests merged in 2022-07, with the labels that each got.

#1508 Add language resistance brave
  docs/browsers.en.md
Labels: c:browsers

#1511 Chore: remove link redirect
  docs/linux-desktop/overview.en.md
Labels: t:correction

#1502 Update Linux pages
  docs/linux-desktop.en.md
  docs/linux-desktop/hardening.en.md
  docs/linux-desktop/overview.en.md
  includes/abbreviations.en.md
Labels: c:os

#1494 Add Signal Configuration and Molly Knowledge Base article
  docs/advanced/signal-configuration-hardening.en.md
  docs/assets/img/messengers/molly.svg
  docs/real-time-communication.en.md
  docs/tools.en.md
  includes/abbreviations.en.md
  mkdocs.yml
Labels: c:guides

#1519 Remove Bromite
  docs/assets/img/browsers/bromite.svg
  docs/browsers.en.md
  docs/tools.en.md
Labels: c:browsers

#1520 Add Brave Android in Mobile browser recommendations
  docs/browsers.en.md
  docs/tools.en.md
Labels: c:browsers

#1518 Remove CalyxOS
  docs/android.en.md
  docs/android/grapheneos-vs-calyxos.en.md
  docs/android/overview.en.md
  docs/assets/img/android/calyxos.svg
  docs/tools.en.md
Labels: c:os

#1540 Fix couple typos VPN & Linux desktop hardening pages
  docs/basics/vpn-overview.en.md
  docs/linux-desktop/hardening.en.md
Labels: c:os, t:correction

#1546 Rephrase GrapheneOS vs CalyxOS page
  docs/android.en.md
  docs/android/grapheneos-vs-calyxos.en.md
Labels: c:os, t:correction

#1548 Changed multifactor to multi-factor
  docs/basics/multi-factor-authentication.en.md
Labels: t:correction

#1552 Rephrase Tails recommendation
  docs/linux-desktop.en.md
Labels: c:os, t:correction

#1555 Update Chrome OS to ChromeOS
  docs/basics/common-threats.en.md
Labels: c:os

#1522 Add link arch system maintenance
  docs/linux-desktop.en.md
  docs/linux-desktop/overview.en.md
Labels: c:os, t:correction

#1577 Add link to gorhill's blocking modes
  docs/browsers.en.md
Labels: c:browsers, t:correction

#1583 Add SimpleLogin linked with Proton
  docs/email.en.md
Labels: c:providers, t:correction

#1578 Add separate desktop and mobile browser pages
  docs/desktop-browsers.en.md
  docs/mobile-browsers.en.md
  docs/tools.en.md
  mkdocs.yml
Labels: c:browsers, t:correction

#1588 Remove magic wormhole
  docs/assets/img/file-sharing-sync/magic_wormhole.png
  docs/file-sharing.en.md
  docs/tools.en.md
Labels: c:software, t:correction
