Repository privacyguides/privacyguides.org, pull requests merged in 2022-08, with the labels that each got.

#1598 Add Proton Drive platforms
  docs/cloud.en.md
Labels: c:software, t:correction

#1597 Fix broken hyperlinks
  docs/tools.en.md
Labels: t:correction

#1602 Add Tor Browser to mobile browsers (Android)
  docs/mobile-browsers.en.md
  docs/tools.en.md
Labels: c:browsers, t:correction

#1617 Fix broken mobile browsers hyperlinks
  docs/tools.en.md
Labels: c:browsers, t:correction

#1608 Update SimpleLogin free aliases number
  docs/email.en.md
Labels: c:providers, t:correction

#1618 Proton VPN 2FA and countries correction
  docs/vpn.en.md
Labels: c:providers, t:correction

#1630 Split mkdocs configuration file
  .github/workflows/pages.yml
  .github/workflows/preview.yml
  README.md
  mkdocs.production.yml
  mkdocs.yml
Labels: c:enhancements, m:contributing

#1633 Fix typo in Tomb section
  docs/encryption.en.md
Labels: c:software, t:correction

#1611 Add Gitlab Syntax For RSS Feed
  docs/android.en.md
  docs/assets/img/android/gfeeds-dark.png
  docs/assets/img/android/gfeeds-light.png
  docs/assets/img/android/rss-apk-dark.png
  docs/assets/img/android/rss-apk-light.png
  docs/assets/img/android/rss-changes-dark.png
  docs/assets/img/android/rss-changes-light.png
Labels: c:software

#1648 Improve mobile experience
  theme/overrides/home.en.html
Labels: t:bug

#1645 Fix word order, typo
  docs/basics/tor-overview.md
Labels: t:correction

#1647 Fix mistakes
  docs/basics/common-threats.en.md
  docs/real-time-communication.en.md
Labels: t:correction

#1653 Remove AdGuard mention in Desktop Browsers page
  docs/desktop-browsers.en.md
Labels: c:browsers, t:correction

#1656 Pull Matrix server configuration
  .github/workflows/pages.yml
  .well-known/matrix/client
  .well-known/matrix/server
Labels: fix:github_actions

#1663 Update discussions link
  mkdocs.yml
Labels: t:bug, m:contributing

#1655 Replace pfSense with OPNsense
  docs/assets/img/router/opnsense.svg
  docs/assets/img/router/pfsense-dark.svg
  docs/assets/img/router/pfsense.svg
  docs/router.en.md
  docs/tools.en.md
Labels: c:os

#1681 Fix Bitlocker for Home edition guide
  docs/encryption.en.md
Labels: c:guides, t:correction

#1669 Adjust Vaultwarden and Molly Listings
  docs/advanced/signal-configuration-hardening.en.md
  docs/assets/img/password-management/vaultwarden-dark.svg
  docs/assets/img/password-management/vaultwarden.svg
  docs/passwords.en.md
  docs/real-time-communication.en.md
  docs/tools.en.md
Labels: c:software

#1682 Update Android app recommendations
  docs/advanced/integrating-metadata-removal.en.md
  docs/advanced/signal-configuration-hardening.en.md
  docs/android.en.md
  docs/android/overview.en.md
  docs/assets/img/android/aurora-store.webp
  docs/assets/img/android/f-droid.svg
  docs/assets/img/data-redaction/exifcleaner.svg
  docs/assets/img/data-redaction/exiferaser.svg
  docs/assets/img/data-redaction/exiftool.png
  docs/assets/img/data-redaction/mat2.svg
  docs/assets/img/data-redaction/metapho.jpg
  docs/assets/img/data-redaction/privacyblur.svg
  docs/assets/img/self-contained-networks/orbot.svg
  docs/data-redaction.en.md
  docs/self-contained-networks.en.md
  docs/tools.en.md
  mkdocs.yml
Labels: c:software, c:os

#1691 Enable social cards
  .github/workflows/pages.yml
  .github/workflows/preview.yml
  Pipfile
  Pipfile.lock
  README.md
  mkdocs.production.yml
  mkdocs.yml
Labels: c:enhancements

#1693 Create release.yml
  .github/workflows/release.yml
  README.md
Labels: fix:github_actions, m:contributing

#1690 Update GrapheneOS
  docs/android.en.md
Labels: c:os, t:correction
