Repository privacyguides/privacyguides.org, pull requests merged in 2022-12, with the labels that each got.

#1901 Recommend against Nextcloud E2EE
  docs/cloud.en.md
Labels: c:software

#1903 Remove DNSCrypt mention for NextDNS
  docs/dns.en.md
Labels: c:providers, t:correction

#1904 Replace F-Droid link
  docs/android.en.md
Labels: t:correction

#1905 Fix search suggestions
  docs/desktop-browsers.en.md
Labels: t:correction

#1906 Fix broken link on suggestions page
  .github/ISSUE_TEMPLATE/config.yml
Labels: t:bug

#1909 Add SimpleX Chat to tools page
  docs/tools.en.md
Labels: t:correction

#1913 Update Filevault for Advanced Data Protection
  docs/encryption.en.md
Labels: c:software, t:correction

#1911 Add Advanced Data Protection to Safari
  docs/mobile-browsers.en.md
Labels: c:browsers, t:correction

#1914 Update Tutanota 2FA to Include Android and iOS
  docs/email.en.md
Labels: c:providers, t:correction

#1917 Remove Advanced Data Protection from Filevault
  docs/encryption.en.md
Labels: c:software, t:correction

#1915 Add Digital Legacy and Account Termination info to Email Providers
  docs/email.en.md
Labels: c:providers, c:enhancements

#1921 Updating blog post link
  docs/basics/vpn-overview.en.md
Labels: c:blog

#1920 Update Android text to Reflect that Andorid 13 is out
  docs/dns.en.md
Labels: c:providers, t:correction

#1924 Elaborate on digital legacy PR
  docs/email.en.md
  includes/abbreviations.en.md
Labels: c:providers, t:correction
