Repository privacyguides/privacyguides.org, pull requests merged in 2022-10, with the labels that each got.

#1825 Clarifications, VPN overview
  docs/basics/vpn-overview.en.md
Labels: t:correction

#1829 Mention Neo Store in DivestOS recommendation
  docs/android.en.md
Labels: t:correction

#1840 Update Tor window setting location
  docs/desktop-browsers.en.md
Labels: c:browsers, t:correction

#1836 Writing review of common-threats.en.md
  docs/basics/common-threats.en.md
Labels: t:correction

#1842 Add links to GrapheneOS vs CalyxOS page
  docs/android/grapheneos-vs-calyxos.en.md
Labels: t:correction

#1750 Add iOS Guide
  docs/ios/configuration.en.md
  mkdocs.yml
Labels: c:guides

#1871 Redirect past links to current pages
  netlify.toml
Labels: fix:seo

#1876 Remove F-Droid Mentions From vpn.md
  docs/vpn.en.md
Labels: t:correction
