Repository privacyguides/privacyguides.org, pull requests merged in 2022-01, with the labels that each got.

#191 Correct logo and dimensions on small screens
  _includes/nav.html
  assets/css/app.scss
Labels: bug

#523 Remove Mailpile
  _includes/legacy/sections/email-clients.html
  assets/img/legacy_svg/3rd-party/mailpile.svg
Labels: software

#522 Update Mullvad Port Forwarding Information
  _includes/legacy/sections/vpn.html
Labels: providers, correction

#238 Updated Cloudflare resolver for Firefox DNS logging policy
  collections/_pages/providers/dns.md
Labels: providers, research required

#546 Adding ControlD to list of DNS providers.
  _data/dns/controld.yml
Labels: providers

#446 Create virtual-insanity
  assets/img/blog/virtual-insanity.jpg
  collections/_posts/2021-11-01-virtual-insanity.md
Labels: blog

#548 Update CalyxOS comparison
  collections/_evergreen/android.html
Labels: os
