Repository privacyguides/privacyguides.org, pull requests merged in 2022-06, with the labels that each got.

#1219 How Tor Works article
  docs/assets/img/how-tor-works/tor-encryption-dark.svg
  docs/assets/img/how-tor-works/tor-encryption.svg
  docs/assets/img/how-tor-works/tor-path-dark.svg
  docs/assets/img/how-tor-works/tor-path.svg
  docs/basics/tor-overview.md
  mkdocs.yml
Labels: c:guides

#1372 Add grid layout for download links
  docs/android.en.md
  docs/assets/stylesheets/extra.css
  docs/browsers.en.md
  docs/calendar-contacts.en.md
  docs/cloud.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/encryption.en.md
  docs/file-sharing.en.md
  docs/metadata-removal-tools.en.md
  docs/multi-factor-authentication.en.md
  docs/news-aggregators.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/productivity.en.md
  docs/real-time-communication.en.md
  docs/self-contained-networks.en.md
  docs/video-streaming.en.md
Labels: c:enhancements

#1310 TM Example
  docs/basics/common-threats.en.md
Labels: c:guides, t:correction

#1311 VPN/Email clean-up
  docs/basics/vpn-overview.en.md
  docs/vpn.en.md
Labels: c:providers, t:correction

#1387 Fix broken links
  docs/about/notices.en.md
  docs/android/grapheneos-vs-calyxos.en.md
  docs/android/overview.en.md
  docs/basics/account-deletion.en.md
  docs/basics/vpn-overview.en.md
  docs/calendar-contacts.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/linux-desktop/overview.en.md
  docs/notebooks.en.md
  docs/search-engines.en.md
  docs/vpn.en.md
Labels: t:correction

#1386 Add Cash option in Protonmail payments
  docs/email.en.md
Labels: t:correction

#1391 Use bigger icons for certain services
  docs/assets/img/email/anonaddy-dark.svg
  docs/assets/img/email/anonaddy.svg
  docs/assets/img/email/mailboxorg.svg
  docs/assets/img/email/mini/anonaddy-dark.svg
  docs/assets/img/email/mini/anonaddy.svg
  docs/assets/img/email/mini/mailboxorg.svg
  docs/assets/img/email/mini/simplelogin.svg
  docs/assets/img/email/mini/startmail-dark.svg
  docs/assets/img/email/mini/startmail.svg
  docs/assets/img/email/mini/tutanota.svg
  docs/assets/img/email/simplelogin.svg
  docs/assets/img/email/startmail-dark.svg
  docs/assets/img/email/startmail.svg
  docs/assets/img/email/tutanota-dark.svg
  docs/assets/img/email/tutanota.svg
  docs/assets/img/search-engines/duckduckgo-dark.svg
  docs/assets/img/search-engines/duckduckgo.svg
  docs/assets/img/search-engines/mini/duckduckgo.svg
  docs/assets/img/search-engines/mini/searxng-wordmark.svg
  docs/assets/img/search-engines/mini/startpage-dark.svg
  docs/assets/img/search-engines/mini/startpage.svg
  docs/assets/img/search-engines/searxng.svg
  docs/assets/img/search-engines/startpage-dark.svg
  docs/assets/img/search-engines/startpage.svg
  docs/assets/img/vpn/mini/mullvad.svg
  docs/assets/img/vpn/mullvad-dark.svg
  docs/assets/img/vpn/mullvad.svg
  docs/email.en.md
  docs/search-engines.en.md
  docs/tools.en.md
  docs/vpn.en.md
Labels: c:enhancements

#1401 Fixed typos
  docs/android/grapheneos-vs-calyxos.en.md
  docs/android/overview.en.md
  docs/basics/common-threats.en.md
  docs/basics/tor-overview.md
  docs/calendar-contacts.en.md
  docs/email.en.md
  docs/real-time-communication.en.md
  docs/vpn.en.md
Labels: t:correction

#1406 Fix 2FA ordering
  docs/multi-factor-authentication.en.md
Labels: t:correction, c:hardware

#1408 Update Calendar and Contact Sync page
  docs/assets/img/calendar-contacts/decsync.svg
  docs/assets/img/calendar-contacts/nextcloud.svg
  docs/calendar-contacts.en.md
  docs/tools.en.md
  includes/abbreviations.en.md
Labels: c:providers, c:software, t:correction

#1405 Update Search Engine page
  docs/search-engines.en.md
  docs/tools.en.md
Labels: c:providers, t:correction

#1423 Productivity page legacy changes
  docs/assets/img/productivity/framadate.svg
  docs/productivity.en.md
  docs/tools.en.md
  includes/abbreviations.en.md
Labels: pr:legacy migration

#1427 Update OnePlus supported devices for DivestOS
  docs/android.en.md
Labels: t:correction

#1432 Minor fix to AdGuard for iOS
  docs/browsers.en.md
Labels: t:correction

#1425 Update VPN Providers page ordering
  docs/vpn.en.md
Labels: c:providers, t:correction

#1421 Update Real Time Communication page ordering
  docs/real-time-communication.en.md
  docs/tools.en.md
Labels: c:software, t:correction

#1422 Update Email Providers page ordering
  docs/email.en.md
  docs/tools.en.md
Labels: c:providers, t:correction

#1443 Add Control D to DNS providers
  docs/dns.en.md
Labels: t:correction

#1449 K-9 and Thunderbird
  docs/email-clients.en.md
Labels: c:software

#1450 Add early 2022 SimpleLogin audit
  docs/email.en.md
Labels: c:providers

#1452 Fix minor typo Linux page
  docs/linux-desktop/hardening.en.md
Labels: c:software, t:correction

#1451 Fix minor typo in Simple Login description
  docs/email.en.md
Labels: c:providers, t:correction

#1469 Move Cryptpad to office suite
  docs/productivity.en.md
Labels: t:correction

#1472 Remove motto Margic Wormhole
  docs/file-sharing.en.md
Labels: c:software, t:correction

#1483 Remove Tahoe-LAFS
  docs/cloud.en.md
  docs/tools.en.md
Labels: c:software, t:correction

#1478 Tools Page reorder and fix
  docs/tools.en.md
Labels: c:providers, c:software, t:correction

#1481 Fix grammar, punctuation and wording on Home page
  docs/index.en.md
Labels: t:correction

#1486 Remove git-annex
  docs/assets/img/cloud/tahoe-lafs-dark.svg
  docs/assets/img/cloud/tahoe-lafs.svg
  docs/assets/img/file-sharing-sync/gitannex.svg
  docs/file-sharing.en.md
  docs/tools.en.md
Labels: c:software, t:correction

#1497 Add 2022 IVPN audit
  docs/vpn.en.md
Labels: c:providers, t:correction

#1496 Add Proton VPN no-logs audit
  docs/vpn.en.md
Labels: c:providers, t:correction

#1495 Add June 2022 audit Mullvad
  docs/vpn.en.md
Labels: c:providers, t:correction

#1444 Update location of Bromite always-incognito option.
  docs/browsers.en.md
Labels: c:software, t:correction

#1480 Fix grammar, punctuation, duplications in Recommendations
  docs/android.en.md
  docs/browsers.en.md
  docs/calendar-contacts.en.md
  docs/cloud.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/encryption.en.md
  docs/file-sharing.en.md
  docs/linux-desktop.en.md
  docs/metadata-removal-tools.en.md
  docs/multi-factor-authentication.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/productivity.en.md
  docs/real-time-communication.en.md
  docs/router.en.md
  docs/search-engines.en.md
  docs/video-streaming.en.md
  docs/vpn.en.md
Labels: t:correction

#1473 Fix grammar, punctuation, duplications in Knowledge Base
  docs/advanced/erasing-data.md
  docs/advanced/integrating-metadata-removal.en.md
  docs/android/grapheneos-vs-calyxos.en.md
  docs/android/overview.en.md
  docs/basics/account-deletion.en.md
  docs/basics/common-threats.en.md
  docs/basics/dns-overview.en.md
  docs/basics/email-security.en.md
  docs/basics/multi-factor-authentication.en.md
  docs/basics/threat-modeling.en.md
  docs/basics/tor-overview.md
  docs/basics/vpn-overview.en.md
  docs/linux-desktop/hardening.en.md
  docs/linux-desktop/overview.en.md
  docs/linux-desktop/sandboxing.en.md
Labels: c:guides, t:correction

#1499 Wording and remove parentheses in Android Overview
  docs/android/overview.en.md
Labels: c:os, t:correction
