Repository privacyguides/privacyguides.org, pull requests merged in 2022-11, with the labels that each got.

#1839 Add Euki & Drip in health section
  docs/assets/img/health/drip.svg
  docs/assets/img/health/euki.svg
  docs/health-and-fitness.en.md
Labels: c:software

#1893 Add SimpleX Chat
  docs/assets/img/messengers/simplex.svg
  docs/real-time-communication.en.md
Labels: c:software

#1780 Add warning about Proton VPN killswitch Intel Macs
  docs/vpn.en.md
Labels: c:providers, t:correction

#1892 Expand Thunderbird description
  docs/email-clients.en.md
Labels: c:software

#1897 Fix Olivia's Mastodon Link
  docs/about/index.md
Labels: t:correction
