Repository privacyguides/privacyguides.org, pull requests merged in 2022-05, with the labels that each got.

#1156 Correct i2p android link
  docs/self-contained-networks.en.md
Labels: c:software, t:correction

#1133 Update email aliasing section
  docs/email.en.md
  mkdocs.yml
Labels: c:providers

#1168 Fix OnlyOffice Linux link
  docs/productivity.en.md
Labels: c:software, t:correction

#1167 Update legal fair use link
  docs/about/notices.en.md
Labels: t:correction

#1166 Add proper Qubes OS download link
  docs/qubes.en.md
Labels: t:correction

#1163 Add more detail to Proton Calendar & Tutanota Calendar
  docs/calendar-contacts.en.md
Labels: c:software, t:correction

#1162 Minor wording update to "Do I Need A VPN?"
  docs/vpn.en.md
Labels: c:providers, t:correction

#1161 Minor updates to email aliasing section (re: #1133)
  docs/email.en.md
Labels: c:providers, t:correction

#1176 Re-recommend Snowflake (#1176)
  docs/assets/img/browsers/snowflake-dark.svg
  docs/assets/img/browsers/snowflake.svg
  docs/browsers.en.md
  docs/stylesheets/extra.css
  docs/tools.en.md
Labels: c:browsers

#1194 Grammar fix in FreedomBox card
  docs/file-sharing.en.md
Labels: c:software, t:correction

#1193 Fix redundant text in the Firefox card
  docs/browsers.en.md
Labels: c:browsers, t:correction

#1220 Magic Wormhole consistency fix
  docs/file-sharing.en.md
Labels: c:software, t:correction

#1218 Fix typo in MFA guide
  docs/security/multi-factor-authentication.en.md
Labels: c:guides, t:correction

#1222 Remove ControlD DNS
  docs/dns.en.md
Labels: c:providers, t:correction

#1224 Add account deletion guide
  docs/assets/img/account-deletion/exposed_passwords.png
  docs/security/account-deletion.en.md
  mkdocs.yml
Labels: c:guides

#1244 Grammar and wording fixes
  docs/basics/account-deletion.en.md
Labels: c:guides, t:correction

#1117 Remove Disroot email recommendation
  docs/assets/img/email/disroot-dark.svg
  docs/assets/img/email/disroot.svg
  docs/assets/img/email/mini/disroot-dark.svg
  docs/assets/img/email/mini/disroot.svg
  docs/email.en.md
  docs/tools.en.md
Labels: c:providers

#1238 Edit ubo to not recommend installing all filter lists
  docs/browsers.en.md
Labels: c:browsers

#923 Add instructions for manually installing APKs
  docs/android.en.md
  docs/assets/img/android/gfeeds-dark.png
  docs/assets/img/android/gfeeds-light.png
Labels: c:software, c:guides

#1261 Change Warning to Danger for Tor Browser Warning Box
  docs/browsers.en.md
Labels: c:browsers, t:correction

#1275 Improve Snowflake section and extension warnings
  docs/browsers.en.md
Labels: c:browsers

#1274 Link to internal pages from overview
  docs/tools.en.md
Labels: c:enhancements

#1276 Listing common threat examples
  .markdownlint.yml
  docs/basics/common-threats.en.md
  docs/basics/threat-modeling.en.md
  docs/index.en.md
  docs/stylesheets/extra.css
  mkdocs.yml
  theme/overrides/home.en.html
Labels: c:guides

#1285 Update 'Common Threats' article
  docs/basics/common-threats.en.md
Labels: t:correction

#1287 Meet accessibility standards with text colors
  docs/stylesheets/extra.css
Labels: c:accessibility

#1272 Remove Mojeek
  docs/assets/img/search-engines/mini/mojeek.svg
  docs/assets/img/search-engines/mojeek.svg
  docs/search-engines.en.md
  docs/tools.en.md
Labels: c:providers, pr:missing discussion

#1292 Clarify Neo Store rebranding
  docs/android.en.md
Labels: t:correction

#1294 Update NewPipe description
  docs/video-streaming.en.md
Labels: t:correction

#1295 Improve Tor Browser description
  docs/browsers.en.md
Labels: t:correction

#1309 Add Librarian LBRY frontend
  docs/assets/img/video-streaming/librarian-dark.svg
  docs/assets/img/video-streaming/librarian.svg
  docs/tools.en.md
  docs/video-streaming.en.md
Labels: c:providers

#937 Removing Jurisdiction Requirements
  docs/email.en.md
  docs/vpn.en.md
Labels: c:providers

#1256 Add article about erasing data securely
  docs/assets/img/erasing-data/shredos.png
  docs/basics/erasing-data.md
  includes/abbreviations.en.md
  mkdocs.yml
Labels: c:guides

#1307 Update the Linux pages
  docs/linux-desktop.en.md
  docs/linux-desktop/hardening.en.md
  docs/linux-desktop/overview.en.md
  docs/linux-desktop/sandboxing.en.md
  includes/abbreviations.en.md
Labels: c:os, t:correction

#1318 New Proton logos
  docs/assets/img/calendar-contacts/mini/proton-calendar.svg
  docs/assets/img/calendar-contacts/proton-calendar.svg
  docs/assets/img/cloud/mini/protondrive.svg
  docs/assets/img/cloud/protondrive.svg
  docs/assets/img/email/mini/protonmail.svg
  docs/assets/img/email/protonmail.svg
  docs/assets/img/vpn/mini/protonvpn.svg
  docs/assets/img/vpn/protonvpn.svg
  docs/tools.en.md
Labels: c:providers, t:correction

#1303 Add Feeder
  docs/assets/img/news-aggregators/feeder.png
  docs/news-aggregators.en.md
  docs/tools.en.md
Labels: c:software

#1332 Correct Proton VPN pricing
  docs/vpn.en.md
Labels: c:providers, t:correction

#1333 Add Flatpak link for Briar
  docs/real-time-communication.en.md
Labels: c:software, t:correction

#1331 Fixes for the Linux Page
  docs/linux-desktop/hardening.en.md
Labels: c:os, t:correction

#1339 Correct Proton Mail zero-access encryption information
  docs/email.en.md
Labels: c:providers, t:correction

#1316 Update recommendation card design
  docs/android.en.md
  docs/assets/img/cloud/cryptee-dark.svg
  docs/assets/img/cloud/cryptee.svg
  docs/assets/img/metadata-removal/exiftool.png
  docs/browsers.en.md
  docs/calendar-contacts.en.md
  docs/cloud.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/encryption.en.md
  docs/file-sharing.en.md
  docs/linux-desktop.en.md
  docs/metadata-removal-tools.en.md
  docs/multi-factor-authentication.en.md
  docs/news-aggregators.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/productivity.en.md
  docs/qubes.en.md
  docs/real-time-communication.en.md
  docs/router.en.md
  docs/search-engines.en.md
  docs/self-contained-networks.en.md
  docs/stylesheets/extra.css
  docs/tools.en.md
  docs/video-streaming.en.md
  docs/vpn.en.md
Labels: c:enhancements, t:correction

#1317 Revert "Remove FairEmail (#1270)"
  docs/assets/img/email-clients/fairemail.svg
  docs/email-clients.en.md
  docs/encryption.en.md
  docs/tools.en.md
Labels: c:software, t:correction

#1173 Separate articles and recommendations
  docs/android/grapheneos-vs-calyxos.en.md
  docs/basics/account-deletion.en.md
  docs/basics/email-security.en.md
  docs/basics/vpn-overview.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/vpn.en.md
  mkdocs.yml
Labels: c:guides

#1346 Fix Briar Flatpak download
  docs/real-time-communication.en.md
Labels: c:software, t:correction

#1350 Data Erasure Grammar Fixes
  docs/basics/erasing-data.md
Labels: c:guides, t:correction

#1353 Fix links in linux hardening guide
  docs/linux-desktop/hardening.en.md
Labels: c:guides, t:correction

#1354 Fix typos on VPN services page
  docs/basics/vpn-overview.en.md
Labels: t:correction

#1355 Improve Colors and Styles
  docs/assets/stylesheets/extra.css
Labels: c:enhancements

#1359 DivestOS updates
  docs/android.en.md
Labels: c:os

#1351 Minify HTML & CSS
  Pipfile
  Pipfile.lock
  README.md
  docs/assets/javascripts/LICENSE.mathjax.txt
  docs/assets/javascripts/feedback.js
  docs/assets/javascripts/mathjax.js
  docs/assets/javascripts/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff
  docs/assets/javascripts/output/chtml/fonts/woff-v2/MathJax_Zero.woff
  docs/assets/stylesheets/home.css
  mkdocs.yml
  theme/overrides/home.en.html
Labels: t:bug

#1306 Update microG on Calyx information
  docs/android.en.md
  docs/android/grapheneos-vs-calyxos.en.md
Labels: c:guides, t:correction
