Repository privacyguides/privacyguides.org, pull requests merged in 2022-04, with the labels that each got.

#827 Fix some typos in the DNS page
  docs/android.md
  docs/blog/2019/08/22/self-hosting-shadowsocks-vpn-outline.md
  docs/blog/2019/10/30/choosing-a-vpn.md
  docs/dns.md
  docs/email-clients.md
Labels: correction

#874 Warning on Firefox privacy blog post (#868)
  docs/blog/2019/11/09/firefox-privacy.md
Labels: browsers, correction

#880 Fix KeepassDX F-Droid link
  docs/passwords.md
Labels: software, correction

#873 Move PGP to own section
  docs/assets/img/encryption-software/gpg4win.svg
  docs/assets/img/encryption-software/gpgtools.png
  docs/assets/img/encryption-software/openkeychain.svg
  docs/encryption.md
Labels: software, correction

#896 "Move Fast and Break Things"
  docs/assets/img/blog/move-fast-and-break-things.jpg
  docs/blog.md
  docs/blog/2022/04/04/move-fast-and-break-things.md
  mkdocs.yml
Labels: blog

#898 Meta information (about us, privacy policy, footer)
  docs/about.md
  docs/about/bounty.md
  docs/about/notices.md
  docs/about/privacy-policy.md
  mkdocs.production.yml
  mkdocs.yml
Labels: legacy migration

#875 Moderate hardware key recommendation
  docs/multi-factor-authentication.md
Labels: hardware

#912 Fix homepage button
  docs/tools.md
  theme/overrides/home.css
  theme/overrides/home.html
Labels: bug, accessibility

#914 Remove homepage footer
  docs/index.md
  theme/overrides/home.html
Labels: enhancements

#922 Fixed warning on the DNDS provider page
  docs/dns.md
Labels: correction

#909 Fix the missing DecSync logo in the tools page
  docs/assets/img/calendar-contacts/decsync.svg
  docs/calendar-contacts.md
  docs/tools.md
Labels: software, correction

#904 Detail the DivestOS hardening
  docs/android.md
Labels: software, correction

#939 Add PG logo icon
  docs/about.md
  theme/.icons/pg/privacyguides.svg
Labels: correction

#946 Update broken links on privacy policy
  docs/about/privacy-policy.md
Labels: correction

#919 Integrating Metadata Removal
  docs/assets/img/integrating-metadata-removal/preview-ios.png
  docs/assets/img/integrating-metadata-removal/preview-macos.png
  docs/assets/img/integrating-metadata-removal/preview-windows.jpg
  docs/assets/img/integrating-metadata-removal/shortcut-ios.png
  docs/assets/img/integrating-metadata-removal/shortcut-macos.png
  docs/metadata-removal-tools.md
  docs/setup/integrating-metadata-removal.md
  mkdocs.yml
Labels: software, correction

#963 Add link to VPN criteria
  docs/vpn.md
Labels: correction

#958 Use styilization of mailcow
  docs/tools.md
Labels: software, correction

#955 De-indent "Where to get your applications"
  docs/android.md
Labels: correction

#862 Update the 2FA page
  docs/android.md
  docs/assets/img/multi-factor-authentication/yubico-otp.png
  docs/multi-factor-authentication.md
  docs/security/multi-factor-authentication.md
  docs/tools.md
  mkdocs.yml
Labels: software, hardware

#895 Add RSS page
  docs/assets/img/news-aggregators/akregator.svg
  docs/assets/img/news-aggregators/fluent-reader.svg
  docs/assets/img/news-aggregators/gfeeds.svg
  docs/assets/img/news-aggregators/handy-news-reader.svg
  docs/assets/img/news-aggregators/miniflux-dark.svg
  docs/assets/img/news-aggregators/miniflux.svg
  docs/assets/img/news-aggregators/netnewswire.png
  docs/assets/img/news-aggregators/newsboat.svg
  docs/news-aggregators.md
  docs/tools.md
  mkdocs.yml
Labels: software

#985 Remove blog
  docs/about/bounty.md
  docs/assets/img/blog/firefox-privacy-2021.png
  docs/assets/img/blog/move-fast-and-break-things.jpg
  docs/assets/img/blog/virtual-insanity.jpg
  docs/blog.md
  docs/blog/2021/09/14/welcome-to-privacy-guides.md
  docs/blog/2021/11/01/virtual-insanity.md
  docs/blog/2021/12/01/firefox-privacy-2021-update.md
  docs/blog/2022/04/04/move-fast-and-break-things.md
  mkdocs.production.yml
  mkdocs.yml
  theme/overrides/blog.css
  theme/overrides/blog.html
Labels: c:blog

#987 Add changelog, deploy on tagged releases
  .github/CODEOWNERS
  .github/workflows/deploy.yml
  CHANGELOG.md
  README.md
Labels: c:enhancements, fix:github_actions, m:contributing

#953 Remove Social Networks & Social News Aggregators
  docs/assets/img/social-media-aggregator/freepost.svg
  docs/assets/img/social-media-aggregator/lemmy.svg
  docs/assets/img/social-media-aggregator/postmill.png
  docs/assets/img/social-media-aggregator/tildes.svg
  docs/assets/img/social-networks/diaspora.svg
  docs/assets/img/social-networks/friendica.svg
  docs/assets/img/social-networks/mastodon.svg
  docs/assets/img/social-networks/movim.svg
  docs/assets/img/social-networks/pixelfed.svg
  docs/assets/img/social-networks/pleroma.svg
  docs/social-networks.md
  docs/social-news-aggregator.md
  docs/tools.md
  mkdocs.yml
Labels: c:software

#995 Add support for localization
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Pipfile
  Pipfile.lock
  README.md
  crowdin.yml
  docs/about.en.md
  docs/about/notices.en.md
  docs/about/privacy-policy.en.md
  docs/android.en.md
  docs/browsers.en.md
  docs/calendar-contacts.en.md
  docs/cloud.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/encryption.en.md
  docs/file-sharing.en.md
  docs/index.en.md
  docs/linux-desktop.en.md
  docs/metadata-removal-tools.en.md
  docs/multi-factor-authentication.en.md
  docs/news-aggregators.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/productivity.en.md
  docs/qubes.en.md
  docs/real-time-communication.en.md
  docs/router.en.md
  docs/search-engines.en.md
  docs/security/multi-factor-authentication.en.md
  docs/self-contained-networks.en.md
  docs/setup/integrating-metadata-removal.en.md
  docs/technology/dns.en.md
  docs/threat-modeling.en.md
  docs/tools.en.md
  docs/video-streaming.en.md
  docs/vpn.en.md
  mkdocs.production.yml
  mkdocs.yml
  theme/overrides/home.en.html
Labels: l10n

#1006 Clarify macOS DNS instructions and reword a sentence
  docs/dns.en.md
Labels: t:correction

#1019 ProtonVPN supports port forwarding Windows
  docs/vpn.en.md
Labels: c:providers, t:correction

#1015 Add right arrows to `Learn more...` links
  docs/tools.en.md
Labels: c:enhancements

#1016 Use annotations for tool notes
  docs/tools.en.md
Labels: c:enhancements

#1017 MFA page grammatical fixes
  docs/assets/img/multi-factor-authentication/fido.png
  docs/multi-factor-authentication.en.md
  docs/security/multi-factor-authentication.en.md
Labels: c:guides, t:correction

#1027 Support asset localization
  crowdin.yml
  docs/assets/img/integrating-metadata-removal/preview-ios.en.png
  docs/assets/img/integrating-metadata-removal/preview-macos.en.png
  docs/assets/img/integrating-metadata-removal/preview-windows.en.jpg
  docs/assets/img/integrating-metadata-removal/shortcut-ios.en.png
  docs/assets/img/integrating-metadata-removal/shortcut-macos.en.png
  docs/assets/img/multi-factor-authentication/fido.en.png
  docs/assets/img/multi-factor-authentication/yubico-otp.en.png
Labels: c:enhancements, l10n

#1038 Minor fix on Linux page
  docs/linux-desktop.en.md
Labels: t:correction

#1032 Link to ECS
  docs/dns.en.md
Labels: t:correction

#1033 Mention OpenQA
  docs/linux-desktop.en.md
Labels: c:os, t:correction

#1030 Reduce number of EXIF links
  docs/metadata-removal-tools.en.md
  docs/setup/integrating-metadata-removal.en.md
Labels: t:correction

#1043 Correct spelling of YouTube
  docs/news-aggregators.en.md
Labels: t:correction

#1048 searx.me link fix
  docs/search-engines.en.md
Labels: t:correction

#1058 Fix capitalization of Exif
  docs/setup/integrating-metadata-removal.en.md
Labels: t:correction

#1053 Split Android page into separate articles and update device recommendations
  docs/android.en.md
  docs/android/grapheneos-vs-calyxos.md
  docs/android/overview.md
  docs/android/security.md
  docs/assets/img/android/google-pixel.png
  docs/threat-modeling.en.md
  mkdocs.yml
Labels: c:os

#1062 Show last revision date on documentation
  .github/workflows/deploy.yml
  Pipfile
  Pipfile.lock
  mkdocs.yml
Labels: c:enhancements

#1060 Use abbreviations across site
  crowdin.yml
  docs/android.en.md
  docs/android/overview.en.md
  docs/android/security.en.md
  docs/browsers.en.md
  docs/calendar-contacts.en.md
  docs/cloud.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/encryption.en.md
  docs/linux-desktop.en.md
  docs/metadata-removal-tools.en.md
  docs/multi-factor-authentication.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/real-time-communication.en.md
  docs/router.en.md
  docs/search-engines.en.md
  docs/security/multi-factor-authentication.en.md
  docs/self-contained-networks.en.md
  docs/setup/integrating-metadata-removal.en.md
  docs/technology/dns.en.md
  docs/tools.en.md
  docs/video-streaming.en.md
  docs/vpn.en.md
  includes/abbreviations.en.md
  mkdocs.yml
Labels: c:enhancements

#1072 Move "NewPipe x SponsorBlock" to NewPipe sub-section
  docs/video-streaming.en.md
Labels: c:software

#1074 Move Android content from overview to security page
  docs/android/overview.en.md
  docs/android/security.en.md
Labels: c:os

#1067 Recommend a custom Android OS
  docs/android/overview.en.md
  docs/android/security.en.md
  includes/abbreviations.en.md
  mkdocs.yml
Labels: c:os, c:guides

#1078 Use dropdown for download links
  docs/android.en.md
  docs/browsers.en.md
  docs/calendar-contacts.en.md
  docs/cloud.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/encryption.en.md
  docs/file-sharing.en.md
  docs/metadata-removal-tools.en.md
  docs/multi-factor-authentication.en.md
  docs/news-aggregators.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/productivity.en.md
  docs/qubes.en.md
  docs/real-time-communication.en.md
  docs/router.en.md
  docs/search-engines.en.md
  docs/self-contained-networks.en.md
  docs/stylesheets/extra.css
  docs/video-streaming.en.md
Labels: c:enhancements

#1082 Remove redundant paragraph on Android overview
  docs/android/overview.en.md
Labels: c:os

#1084 Replace emojis with icons
  docs/android.en.md
  docs/android/overview.en.md
  docs/browsers.en.md
  docs/video-streaming.en.md
Labels: c:enhancements

#1097 Fix missing tools entries
  docs/tools.en.md
Labels: c:software, t:correction

#1089 Set toc_depth of 4
  mkdocs.yml
Labels: c:enhancements

#1092 Reduce the number of admonitions across the site
  docs/browsers.en.md
  docs/cloud.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/encryption.en.md
  docs/metadata-removal-tools.en.md
  docs/multi-factor-authentication.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/router.en.md
  docs/search-engines.en.md
  docs/setup/integrating-metadata-removal.en.md
  docs/vpn.en.md
Labels: t:correction

#1086 Make the Android pages more consistent
  docs/android.en.md
  docs/android/grapheneos-vs-calyxos.en.md
  docs/android/overview.en.md
  docs/browsers.en.md
  docs/video-streaming.en.md
  includes/abbreviations.en.md
Labels: c:os, t:correction

#1095 Update primary button text
  docs/android.en.md
  docs/browsers.en.md
  docs/calendar-contacts.en.md
  docs/cloud.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/encryption.en.md
  docs/file-sharing.en.md
  docs/linux-desktop.en.md
  docs/metadata-removal-tools.en.md
  docs/multi-factor-authentication.en.md
  docs/news-aggregators.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/productivity.en.md
  docs/qubes.en.md
  docs/real-time-communication.en.md
  docs/router.en.md
  docs/search-engines.en.md
  docs/self-contained-networks.en.md
  docs/video-streaming.en.md
  docs/vpn.en.md
Labels: c:enhancements

#1099 Change SearX to more maintained SearXNG
  docs/assets/img/search-engines/mini/searxng-wordmark.svg
  docs/assets/img/search-engines/mojeek.svg
  docs/assets/img/search-engines/searx.svg
  docs/assets/img/search-engines/searxng.svg
  docs/search-engines.en.md
  docs/tools.en.md
Labels: c:providers

#1112 Plausible analytics
  docs/about/privacy-policy.en.md
  mkdocs.yml
  theme/partials/integrations/analytics/plausible.html
Labels: c:enhancements

#1131 Update Firefox for Android description
  docs/browsers.en.md
Labels: c:browsers, t:correction

#1132 Update DuckDuckGo description and logos
  docs/assets/img/search-engines/duckduckgo-dark.svg
  docs/assets/img/search-engines/duckduckgo.svg
  docs/assets/img/search-engines/mini/duckduckgo.svg
  docs/search-engines.en.md
  docs/tools.en.md
Labels: c:providers, t:correction

#1134 Add privacy policies for email providers
  docs/email.en.md
Labels: c:providers, t:correction

#1135 Update Startpage logos
  docs/assets/img/search-engines/mini/startpage-dark.svg
  docs/assets/img/search-engines/mini/startpage.svg
  docs/assets/img/search-engines/startpage-dark.svg
  docs/assets/img/search-engines/startpage.svg
  docs/search-engines.en.md
  docs/tools.en.md
Labels: c:providers, t:correction

#1136 Update footer social links
  mkdocs.yml
  theme/.icons/pg/matrix.svg
Labels: t:correction
