Repository privacyguides/privacyguides.org, pull requests merged in 2023-10, with the labels that each got.

#2287 Update Tutanota aliases
  docs/email.md
Labels: t:correction

#2283 Update SimpleX chat now supports MacOS and Linux
  docs/real-time-communication.md
Labels: t:correction

#2290 Provide example of QNAME minimization
  docs/advanced/dns-overview.md
Labels: t:correction

#2294 Recommend Obtainium
  docs/android.md
  docs/tools.md
  theme/assets/img/android/obtainium.svg
Labels: c:software

#2297 Add note about Securitum security audit to addy.io
  docs/email.md
Labels: c:providers

#2298 Fix indent in email marketing criteria
  docs/email.md
Labels: t:correction

#2299 Re-add Onion Browser
  docs/tools.md
  docs/tor.md
  theme/assets/img/self-contained-networks/onion_browser.svg
Labels: c:browsers

#2302 Add more information about Bitlocker
  docs/encryption.md
Labels: c:software, t:correction

#2303 MAC address randomization update
  docs/os/macos-overview.md
Labels: c:os, t:correction

#2312 Add Proton Calendar App Store link
  docs/calendar.md
Labels: c:providers

#2292 Recommend "Max Protection" DNS over HTTPS in Firefox
  docs/desktop-browsers.md
Labels: c:browsers

#2310 Add "ente Auth" TOTP app
  docs/multi-factor-authentication.md
  docs/tools.md
  theme/assets/img/multi-factor-authentication/ente-auth.png
Labels: c:providers

#2295 Open-source hyphens fix
  docs/about/criteria.md
  docs/about/index.md
  docs/about/notices.md
  docs/about/privacytools.md
  docs/android.md
  docs/basics/common-misconceptions.md
  docs/cloud.md
  docs/data-redaction.md
  docs/desktop.md
  docs/email-clients.md
  docs/encryption.md
  docs/frontends.md
  docs/multi-factor-authentication.md
  docs/notebooks.md
  docs/os/android-overview.md
  docs/os/linux-overview.md
  docs/passwords.md
  docs/productivity.md
  docs/router.md
  docs/vpn.md
Labels: t:correction

#2314 Update pixel updates to 7 years
  docs/android.md
Labels: c:os, t:correction

#2271 Add warning about Brave's "referral code" system
  docs/desktop-browsers.md
Labels: c:browsers

#2321 Update and Add URLs
  docs/android.md
  docs/email-clients.md
  docs/news-aggregators.md
  docs/tor.md
Labels: c:software, t:correction
