Repository privacyguides/privacyguides.org, pull requests merged in 2023-12, with the labels that each got.

#2342 Add uBlock Origin Lite
  docs/basics/common-threats.md
  docs/desktop-browsers.md
  docs/os/android-overview.md
  docs/tools.md
  docs/vpn.md
  theme/assets/img/browsers/ublock_origin_lite.svg
Labels: c:browsers

#2344 Include forgetful browsing recommendation for Brave
  docs/desktop-browsers.md
Labels: c:browsers

#2350 Discuss other variants Fedora immutable desktops
  docs/desktop.md
Labels: c:os

#2352 Fix typo JS requirment Frontends page
  docs/frontends.md
Labels: c:software

#2356 Update server count for VPNs
  docs/vpn.md
Labels: c:providers
