Repository privacyguides/privacyguides.org, pull requests merged in 2023-11, with the labels that each got.

#2319 Remove i18n link from README.md
  README.md
Labels: t:correction

#2293 Recommend F-Droid Basic over Neo Store
  docs/android.md
  docs/tools.md
Labels: c:software

#2325 Replace "Tutanota" with "Tuta"
  docs/calendar.md
  docs/email.md
  docs/tools.md
  theme/assets/img/calendar/tuta.svg
  theme/assets/img/calendar/tutanota-dark.svg
  theme/assets/img/email/tuta.svg
Labels: c:providers, t:correction

#2322 Clarify and modernize VPN and Tor advice
  docs/advanced/tor-overview.md
  docs/android.md
  docs/basics/common-threats.md
  docs/basics/vpn-overview.md
  docs/desktop.md
  docs/os/qubes-overview.md
  docs/tor.md
Labels: c:software, c:enhancements

#2102 Add Photo Management Recommendations
  config/mkdocs-offline.yml
  config/mkdocs.en.yml
  config/mkdocs.fr.yml
  config/mkdocs.he.yml
  config/mkdocs.nl.yml
  docs/photo-management.md
  docs/tools.md
  theme/assets/img/cover/photo-management.webp
  theme/assets/img/photo-management/ente-dark.svg
  theme/assets/img/photo-management/ente.svg
  theme/assets/img/photo-management/photoprism.svg
  theme/assets/img/photo-management/stingle-dark.png
  theme/assets/img/photo-management/stingle.png
Labels: c:providers

#2329 Tuta now supports subfolders
  docs/email.md
Labels: c:providers, t:correction

#2328 Clarify Google Play Services permissions
  docs/os/android-overview.md
Labels: c:os, t:correction

#2326 Clarify data breach risk with OAuth
  docs/basics/account-creation.md
Labels: t:correction

#2333 MAT2 Nautilus extension deprecated
  docs/data-redaction.md
Labels: c:software, t:correction

#2324 Code of Conduct updated grammar and punctuation
  docs/CODE_OF_CONDUCT.md
Labels: t:correction

#2334 AdGuard DNS supports ECS as of v0.3.1
  docs/dns.md
Labels: c:providers, t:correction

#2336 AdGuard supports DoQ
  docs/dns.md
Labels: c:providers, t:correction

#2332 Clarify Notesnook encryption
  docs/notebooks.md
Labels: c:software, t:correction

#2340 Add Proton Drive macOS download
  docs/cloud.md
Labels: c:providers

#2337 Fix dead links
  docs/notebooks.md
  docs/real-time-communication.md
Labels: t:correction
