Repository privacyguides/privacyguides.org, pull requests merged in 2023-02, with the labels that each got.

#1951 Mention "Atlas of Surveillance" in the "Mass Surveillance" section
  docs/basics/common-threats.en.md
Labels: c:enhancements

#1957 Add Accrescent download link for ExifEraser
  docs/data-redaction.en.md
Labels: c:software

#1961 Adds Windows & Linux download for briar desktop
  docs/real-time-communication.en.md
Labels: c:software

#1962 Remove "Other Messengers" and "Cross Platform Messengers"
  docs/real-time-communication.en.md
Labels: c:software, t:correction

#1963 Fix broken links across the site
  docs/android.en.md
  docs/cloud.en.md
  docs/desktop.en.md
  docs/multi-factor-authentication.en.md
  docs/productivity.en.md
  docs/tor.en.md
Labels: t:correction

#1941 Reported issues from Crowdlin
  docs/basics/account-creation.en.md
  docs/vpn.en.md
Labels: t:correction

#1965 fix typo in qubes OS overview
  docs/os/qubes-overview.en.md
Labels: c:os, t:correction

#1968 Disable Dependabot for Python dependencies
  .github/dependabot.yml
Labels: fix:python

#1970 Fix Briar id in Privacy Tools page
  docs/tools.en.md
Labels: c:software, t:correction

#1971 fix typo Linux overview
  docs/os/linux-overview.en.md
Labels: c:os, t:correction

#1973 Fix admonitions
  docs/basics/common-threats.en.md
  docs/desktop-browsers.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/encryption.en.md
  docs/vpn.en.md
Labels: t:bug

#1975 Move Cryptee to Notebooks section
  docs/assets/img/notebooks/cryptee-dark.svg
  docs/assets/img/notebooks/cryptee.svg
  docs/cloud.en.md
  docs/notebooks.en.md
  docs/tools.en.md
Labels: c:software

#1955 Adds Yattee to "Frontends"
  docs/assets/img/frontends/yattee.svg
  docs/frontends.en.md
  docs/tools.en.md
Labels: c:software

#1981 Remove incorrect information about Tutanota
  docs/email.en.md
Labels: c:providers, t:correction

#1979 Remove Microsoft Office suggestion
  docs/productivity.en.md
Labels: c:software

#1982 Improve email criteria
  docs/email.en.md
Labels: c:providers

#1985 Correct dead link in DoH description
  docs/advanced/dns-overview.en.md
Labels: c:providers

#1986 Other uBO lists
  docs/desktop-browsers.en.md
Labels: c:software

#1992 Disable Firefox Accounts telemetry
  docs/desktop-browsers.en.md
Labels: c:browsers

#1984 Mention linux updates
  docs/os/linux-overview.en.md
Labels: c:os

#1995 fix typo in Email Services
  docs/email.en.md
Labels: t:correction

#1980 Define criteria on all recommendation pages
  docs/android.en.md
  docs/assets/img/calendar/proton-calendar.svg
  docs/assets/img/calendar/tutanota-dark.svg
  docs/assets/img/calendar/tutanota.svg
  docs/assets/img/productivity/nextcloud.svg
  docs/calendar.en.md
  docs/cloud.en.md
  docs/data-redaction.en.md
  docs/desktop-browsers.en.md
  docs/desktop.en.md
  docs/dns.en.md
  docs/email-clients.en.md
  docs/email.en.md
  docs/encryption.en.md
  docs/file-sharing.en.md
  docs/frontends.en.md
  docs/mobile-browsers.en.md
  docs/multi-factor-authentication.en.md
  docs/news-aggregators.en.md
  docs/notebooks.en.md
  docs/passwords.en.md
  docs/productivity.en.md
  docs/real-time-communication.en.md
  docs/router.en.md
  docs/search-engines.en.md
  docs/tools.en.md
  docs/video-streaming.en.md
  docs/vpn.en.md
  mkdocs.yml
  netlify.toml
Labels: c:enhancements

#2011 Clarify PGP on Apple Mail
  docs/email-clients.en.md
Labels: c:software, t:correction

#2012 Warning about k-9 reply mailing list
  docs/email-clients.en.md
Labels: c:software, t:correction

#2001 Add LibreTube
  docs/assets/img/frontends/libretube-dark.svg
  docs/assets/img/frontends/libretube.svg
  docs/frontends.en.md
  docs/tools.en.md
Labels: c:software

#2017 Fix typo in frontends page
  docs/frontends.en.md
Labels: c:software, t:correction

#2016 Fix grammar on LibreTube entry
  docs/frontends.en.md
Labels: c:software, t:correction

#2018 Fix Black Line on Brave
  docs/assets/stylesheets/home.css
Labels: t:bug

#2027 Fix mistakes in various files
  docs/android.en.md
  docs/basics/account-creation.en.md
  docs/basics/passwords-overview.en.md
  docs/basics/vpn-overview.en.md
  docs/encryption.en.md
  docs/frontends.en.md
  docs/router.en.md
  includes/abbreviations.en.md
Labels: t:correction

#2033 Use consistent language across articles for open-source
  docs/desktop-browsers.en.md
  docs/file-sharing.en.md
  docs/frontends.en.md
  docs/multi-factor-authentication.en.md
  docs/news-aggregators.en.md
  docs/productivity.en.md
Labels: t:correction, l10n

#2034 Fix MFA consistency in criteria
  docs/cloud.en.md
  docs/productivity.en.md
Labels: t:correction, l10n

#2035 Add FR specific, multi languages context
  docs/basics/common-threats.en.md
  docs/basics/passwords-overview.en.md
Labels: t:correction

#2052 F-Droid consistency
  docs/android.en.md
Labels: c:os, t:correction
