Repository privacyguides/privacyguides.org, pull requests merged in 2023-06, with the labels that each got.

#2183 Fix Standard Notes Security Audit Link
  docs/notebooks.md
Labels: c:software, t:bug

#2188 Fix broken link on cryptocurrency page
  docs/cryptocurrency.md
Labels: t:correction

#2186 Fix Netnewswire privacy policy link.
  docs/news-aggregators.md
Labels: t:correction

#2191 Fix inaccurate port forwarding information for ProtonVPN
  docs/vpn.md
  includes/abbreviations.en.txt
Labels: c:providers, t:correction

#2192 Fix indentation of Why Privacy Matters article
  docs/basics/why-privacy-matters.md
Labels: t:bug, l10n

#2176 Add Notesnook
  docs/notebooks.md
  docs/tools.md
  theme/assets/img/notebooks/notesnook.svg
Labels: c:software

#2200 Fix typo in Privacy Matters page
  docs/basics/why-privacy-matters.md
Labels: t:correction

#2199 Add static 404 page
  .gitignore
  crowdin.yml
  docs/404.md
  netlify.toml
  static/i18n/404.en.html
Labels: t:bug

#2211 Change Seahorse link
  docs/basics/account-deletion.md
Labels: t:correction

#2212 Normalize on "Forward Secrecy"
  docs/real-time-communication.md
  docs/vpn.md
  includes/abbreviations.en.txt
Labels: t:correction

#2214 Fix typo on mobile browser page
  docs/mobile-browsers.md
Labels: t:correction

#2215 IVPN announces removal of port forwarding
  docs/tools.md
  docs/vpn.md
Labels: c:providers, t:correction

#2217 Fix inaccurate info about Safari SIP
  docs/mobile-browsers.md
Labels: c:browsers, t:correction
