Repository privacyguides/privacyguides.org, pull requests merged in 2023-07, with the labels that each got.

#2218 Remove old BSD links
  docs/file-sharing.md
  docs/productivity.md
Labels: c:software, t:correction

#2226 Fix zram link
  docs/os/linux-overview.md
Labels: t:correction

#2227 Fix Phoronix links
  docs/os/linux-overview.md
Labels: t:correction

#2221 Mention how to get channel ID
  docs/news-aggregators.md
Labels: t:correction

#2108 Add Skiff Mail
  docs/email.md
  docs/tools.md
  theme/assets/img/email/skiff-mail.svg
Labels: c:providers

#2224 Translation page
  config/mkdocs-common.yml
  config/mkdocs-offline.yml
  config/mkdocs.en.yml
  config/mkdocs.es.yml
  config/mkdocs.fr.yml
  config/mkdocs.he.yml
  config/mkdocs.it.yml
  config/mkdocs.nl.yml
  docs/meta/translations.md
  includes/strings.en.yml
  theme/main.html
Labels: l10n

#2231 Remove Cake Pay
  docs/financial-services.md
  docs/tools.md
  theme/assets/img/financial-services/cakepay.svg
Labels: c:providers, t:correction

#2223 Revert pride month logos
  theme/partials/logo.html
Labels: t:correction

#2234 Add onion-location header
  Pipfile.lock
  README.md
  config/mkdocs-common.yml
  theme/main.html
  theme/partials/header.html
Labels: c:enhancements

#2236 Re-write fullwidth part
  docs/meta/translations.md
Labels: t:correction

#2150 Add macOS overview
  config/mkdocs.en.yml
  config/mkdocs.es.yml
  config/mkdocs.fr.yml
  config/mkdocs.he.yml
  config/mkdocs.it.yml
  config/mkdocs.nl.yml
  docs/os/macos-overview.md
Labels: c:os, c:guides

#2237 MFA - Nitrokey HOTP/TOTP warning - correct sentence grammar
  docs/multi-factor-authentication.md
Labels: t:correction

#2193 Enable Chinese Traditional Translation
  config/layouts/custom.yml
  config/mkdocs-common.yml
  config/mkdocs.zh-Hant.yml
  includes/strings.en.yml
  netlify.toml
  static/_redirects
  theme/assets/stylesheets/lang-zh-Hant.css
  theme/main.html
Labels: l10n

#2225 Enable Russian Translation
  config/layouts/custom.yml
  config/mkdocs-common.yml
  config/mkdocs.ru.yml
  netlify.toml
  static/_redirects
  theme/assets/stylesheets/lang-ru.css
  theme/main.html
Labels: l10n

#2239 Remove video streaming section
  config/mkdocs-offline.yml
  config/mkdocs.en.yml
  config/mkdocs.es.yml
  config/mkdocs.fr.yml
  config/mkdocs.he.yml
  config/mkdocs.it.yml
  config/mkdocs.nl.yml
  config/mkdocs.ru.yml
  config/mkdocs.zh-Hant.yml
  docs/tools.md
  docs/video-streaming.md
  theme/assets/img/cover/video-streaming.png
  theme/assets/img/video-streaming/lbry.svg
Labels: c:software

#2246 Change regarding "Upgrade connections to HTTPS" on Brave Android
  docs/mobile-browsers.md
Labels: t:correction

#2253 Place Brave's Web3 settings on multiple lines
  docs/desktop-browsers.md
Labels: t:correction

#2255 Update countries VPN providers
  docs/vpn.md
Labels: c:providers, t:correction
