Repository privacyguides/privacyguides.org, pull requests merged in 2023-04, with the labels that each got.

#2113 Clarify source availability in MFA criteria
  docs/multi-factor-authentication.md
Labels: t:correction

#2121 Don't recommend Orbot IsolateDestAddr
  docs/tor.md
Labels: c:software, t:correction

#2124 Browser configuration updates
  docs/desktop-browsers.md
Labels: c:browsers, t:correction

#2126 Fix inconsistency
  docs/frontends.md
  docs/notebooks.md
Labels: t:correction

#2127 Add translation notice to bottom of every page
  includes/strings.en.yml
  theme/main.html
Labels: l10n

#2129 More descriptive title tags
  docs/android.md
  docs/basics/account-creation.md
  docs/basics/email-security.md
  docs/basics/threat-modeling.md
  docs/basics/vpn-overview.md
  docs/cloud.md
  docs/cryptocurrency.md
  docs/data-redaction.md
  docs/desktop-browsers.md
  docs/email.md
  docs/encryption.md
  docs/index.md
  docs/mobile-browsers.md
  docs/passwords.md
  docs/real-time-communication.md
  docs/search-engines.md
  docs/tools.md
  docs/tor.md
  docs/vpn.md
  theme/main.html
Labels: fix:seo

#2123 Clarify Auditor's supported devices
  docs/android.md
Labels: c:software, t:correction

#2132 Change inaccurate wording for DNS providers
  docs/dns.md
Labels: c:providers, t:correction

#2139 Add Accrescent & Play Store Link For IVPN
  docs/vpn.md
Labels: c:software

#2141 Remove Play Store link for shelter
  docs/android.md
Labels: c:software, t:correction

#2143 Remove mention of built-in Twitter support for Netnewswire
  docs/news-aggregators.md
Labels: c:software, t:correction

#2145 Add mention of Apple Mail's Protect Mail Activity feature
  docs/email-clients.md
Labels: c:software

#2151 Fix 1password privacy policy link
  docs/passwords.md
Labels: c:software, t:correction
