Repository privacyguides/privacyguides.org, pull requests merged in 2023-03, with the labels that each got.

#2060 Fix #1930
  theme/partials/header.html
Labels: t:bug

#2030 Permissions and Tracking (Android)
  docs/os/android-overview.md
Labels: c:os

#2070 SEO tag fixes
  _redirects
  docs/404.md
  netlify.toml
  theme/main.html
  theme/partials/header.html
Labels: fix:seo, l10n

#1068 Add private payment methods overview
  config/mkdocs.en.yml
  config/mkdocs.fr.yml
  config/mkdocs.he.yml
  config/mkdocs.nl.yml
  docs/advanced/payments.md
  docs/android.md
  docs/cryptocurrency.md
  docs/dns.md
  docs/email.md
  docs/financial-services.md
  docs/tools.md
  docs/tor.md
  docs/vpn.md
  theme/assets/img/cryptocurrency/monero.svg
  theme/assets/img/financial-services/cakepay.svg
  theme/assets/img/financial-services/coincards.svg
  theme/assets/img/financial-services/mysudo-dark.svg
  theme/assets/img/financial-services/mysudo.svg
  theme/assets/img/financial-services/privacy_com-dark.svg
  theme/assets/img/financial-services/privacy_com.svg
Labels: c:software

#2083 Remove notice that the protondrive app is not opensource.
  docs/cloud.md
Labels: t:correction

#2075 Add page descriptions to docs
  docs/advanced/communication-network-types.md
  docs/advanced/dns-overview.md
  docs/advanced/tor-overview.md
  docs/android.md
  docs/basics/account-creation.md
  docs/basics/account-deletion.md
  docs/basics/common-misconceptions.md
  docs/basics/common-threats.md
  docs/basics/email-security.md
  docs/basics/multi-factor-authentication.md
  docs/basics/passwords-overview.md
  docs/basics/threat-modeling.md
  docs/basics/vpn-overview.md
  docs/calendar.md
  docs/cloud.md
  docs/data-redaction.md
  docs/desktop-browsers.md
  docs/desktop.md
  docs/dns.md
  docs/email-clients.md
  docs/email.md
  docs/encryption.md
  docs/file-sharing.md
  docs/frontends.md
  docs/kb-archive.md
  docs/mobile-browsers.md
  docs/multi-factor-authentication.md
  docs/news-aggregators.md
  docs/notebooks.md
  docs/os/android-overview.md
  docs/os/linux-overview.md
  docs/os/qubes-overview.md
  docs/passwords.md
  docs/productivity.md
  docs/real-time-communication.md
  docs/router.md
  docs/search-engines.md
  docs/tools.md
  docs/tor.md
  docs/video-streaming.md
  docs/vpn.md
Labels: fix:seo

#2095 Use GitHub issue form syntax
  .github/ISSUE_TEMPLATE/1_Content_Correction.md
  .github/ISSUE_TEMPLATE/1_Content_Correction.yml
  .github/ISSUE_TEMPLATE/2_Website_Issues.md
  .github/ISSUE_TEMPLATE/2_Website_Issues.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: m:contributing

#2100 Recommend Tresorit
  docs/cloud.md
  docs/tools.md
  theme/assets/img/cloud/tresorit.svg
Labels: c:providers

#2098 Update website metadata
  CITATION.cff
  Pipfile
  README.md
  _redirects
  config/mkdocs.en.yml
  config/mkdocs.fr.yml
  config/mkdocs.he.yml
  config/mkdocs.nl.yml
  config/mkdocs.offline.yml
  docs/about/index.md
  docs/about/notices.md
Labels: m:contributing
