Repository privacyguides/privacyguides.org, pull requests merged in 2023-01, with the labels that each got.

#1925 VPN server update
  docs/vpn.en.md
Labels: c:providers, t:correction

#1926 Add ProxiTok
  docs/assets/img/frontends/proxitok.png
  docs/frontends.en.md
Labels: c:providers

#1933 Criteria updates to email: Require export and headers
  docs/email.en.md
Labels: c:providers

#1929 Use SVG for ProxiTok and fix button
  docs/assets/img/frontends/proxitok.png
  docs/assets/img/frontends/proxitok.svg
  docs/frontends.en.md
Labels: c:providers

#1935 Add iOS download to Proton Drive
  docs/cloud.en.md
Labels: c:providers, t:correction

#1936 Remove redundant/broken links from Psono description
  docs/passwords.en.md
Labels: c:software, t:correction

#1937 Add note on built-in password managers
  docs/passwords.en.md
Labels: c:software

#1934 Remove macOS/iOS config profile info
  docs/dns.en.md
Labels: c:providers, t:correction

#1943 Remove DNSCrypt support for ControlD
  docs/dns.en.md
Labels: c:providers, t:correction

#1944 Prefer Anycast or Geosteering support
  docs/dns.en.md
Labels: c:providers

#1948 Update mullvad countries
  docs/vpn.en.md
Labels: c:providers, t:correction

#1950 Fix broken link
  .github/ISSUE_TEMPLATE/config.yml
Labels: t:bug

#1952 Updates to Brave description
  docs/desktop-browsers.en.md
  docs/mobile-browsers.en.md
Labels: c:browsers, t:correction

#1959 DoH/3 support for AdGuard, NextDNS and Cloudflare
  docs/dns.en.md
Labels: c:providers, t:correction
