Repository privacyguides/privacyguides.org, pull requests merged in 2023-09, with the labels that each got.

#2275 Add Proton Drive Windows
  docs/cloud.md
Labels: c:software

#2277 Update financial-services.md with note about MySudo's iOS exclusivity
  docs/financial-services.md
Labels: t:correction

#2278 Update Proton Calendar information
  docs/calendar.md
Labels: c:software

#2280 Update feeder repo url
  docs/news-aggregators.md
Labels: c:software, t:correction

#2282 Remove bogus link
  docs/os/ios-overview.md
Labels: t:correction

#2281 Startpage, mention Bing as source
  docs/search-engines.md
Labels: t:correction
