Repository privacyguides/privacyguides.org, pull requests merged in 2023-05, with the labels that each got.

#2152 Update NetNewsWire icon
  theme/assets/img/news-aggregators/netnewswire.png
Labels: c:software, t:correction

#2144 Remove redundant statements in frontends page
  docs/frontends.md
Labels: c:software, t:correction

#2148 Say OAuth instead of SSO
  docs/basics/account-creation.md
Labels: c:guides, t:correction

#2142 Clean up tor page
  docs/tor.md
Labels: c:software, t:bug

#2154 add DoQ to NextDNS
  docs/dns.md
Labels: c:providers, t:correction, status:research required

#2158 Update Tresorit jurisdiction
  docs/cloud.md
Labels: c:software, t:correction

#2159 Remove Librarian
  docs/frontends.md
  docs/tools.md
  theme/assets/img/frontends/librarian-dark.svg
  theme/assets/img/frontends/librarian.svg
Labels: c:software

#2164 Update Brave wallet settings
  docs/desktop-browsers.md
Labels: c:browsers, t:correction

#2166 Remove Startmail, as it's not zero-knowledge
  docs/email.md
  docs/tools.md
  theme/assets/img/email/startmail-dark.svg
  theme/assets/img/email/startmail.svg
Labels: c:providers

#2170 Fix security.txt
  netlify.toml
  static/_redirects
  static/well-known/openpgpkey/hu/dnrefmbtd6i58w8xfy4imj94cmbw3u3h
  static/well-known/openpgpkey/policy
  static/well-known/security.txt
Labels: t:bug

#2169 Remove prohibition on US-based email providers
  docs/email.md
Labels: c:providers

#2165 Add criteria for pastebin services
  docs/productivity.md
Labels: c:software
