Repository privacyguides/privacyguides.org, pull requests merged in 2024-09, with the labels that each got.

#2738 update: Note beta status of GPG Suite on macOS Sonoma
  docs/email-clients.md
  docs/encryption.md
Labels: c:software

#2742 update: Correct advice to hide OS info from network on GrapheneOS
  docs/android/distributions.md
Labels: c:os, t:correction

#2746 fix: Remove Piped Being Able to Play Age Restricted Videos
  docs/frontends.md
Labels: t:correction

#2750 update(blog)!: Proton Wallet review
  blog/.authors.yml
  blog/assets/images/proton-wallet-review/1.png
  blog/assets/images/proton-wallet-review/2.png
  blog/assets/images/proton-wallet-review/3.png
  blog/assets/images/proton-wallet-review/4.png
  blog/author/jonah.md
  blog/posts/proton-wallet-review.md
  docs/about.md
  docs/index.md
  mkdocs.blog.yml
  theme/assets/img/cryptocurrency/proton-wallet.svg
  theme/assets/stylesheets/extra.css
  theme/blog-post.html
  theme/layouts/blog.yml
  theme/main.html
  theme/partials/content.html
Labels: c:blog, ci:build blog

#2754 update(blog)!: Bad-faith argument policy
  blog/posts/bad-faith-arguments.md
Labels: m:contributing, ci:build blog

#2751 update(blog): Add links to Proton Mail and Proton VPN
  blog/posts/proton-wallet-review.md
Labels: t:correction

#2764 update(blog)!: Onion Browser review
  Pipfile
  Pipfile.lock
  blog/assets/images/onion-browser-review/21A92967-2E47-4317-AB2E-C0F732673C3E_1_102_o.jpeg
  blog/assets/images/onion-browser-review/2774018C-C4DD-419C-9D77-9BE8E5A51A19_1_102_o.jpeg
  blog/assets/images/onion-browser-review/51B33FA1-D9B4-4EF4-82C6-259568C845EC_1_102_o.jpeg
  blog/assets/images/onion-browser-review/757A93D0-CCCB-4743-8AF2-17B001EC774A_1_102_o.jpeg
  blog/assets/images/onion-browser-review/87651D0E-EFE0-4C0F-98E7-9898EBA74334_1_102_o.jpeg
  blog/assets/images/onion-browser-review/8A3E82E7-128E-4B3B-B8BB-276063226D41_1_102_o.jpeg
  blog/assets/images/onion-browser-review/C3252F74-C6C1-4616-B3CD-17EA1183BE0C_1_102_o.jpeg
  blog/assets/images/onion-browser-review/D0A2D20B-5550-4C1F-8FC6-F6D84AEBDF13_1_102_o.jpeg
  blog/posts/onion-browser-review.md
  docs/tor.md
  mkdocs.blog.yml
Labels: c:blog, ci:build blog

#2753 docs(blog): Publish editorial policy for news articles
  blog/author/dngray.md
  blog/editorial.md
  mkdocs.blog.yml
  theme/blog-post.html
Labels: m:contributing, ci:build blog

#2767 fix: Replace Broken Invidious links with YouTube
  docs/advanced/tor-overview.md
Labels: t:correction

#2759 update: Add list of sites not supported by removal services
  docs/data-broker-removals.md
Labels: c:providers
