Repository privacyguides/privacyguides.org, pull requests merged in 2024-06, with the labels that each got.

#2594 Create new "Hardware" section
  docs/basics/multi-factor-authentication.md
  docs/basics/passwords-overview.md
  docs/multi-factor-authentication.md
  docs/security-keys.md
  docs/tools.md
  includes/strings.en.env
  mkdocs.yml
  theme/assets/img/security-keys/mini/nitrokey.svg
  theme/assets/img/security-keys/mini/yubico.svg
  theme/assets/img/security-keys/nitrokey.jpg
  theme/assets/img/security-keys/yubico-security-key.webp
  theme/assets/img/security-keys/yubikey.png
Labels: c:enhancements, c:hardware

#2607 fix: typo in Email Security page (email-security.md)
  docs/basics/email-security.md
Labels: t:correction

#2610 ios-overview: Update Find My description
  docs/android.md
  docs/os/ios-overview.md
Labels: c:os, t:correction

#2615 desktop-browsers: Update Brave configuration and apply writing style to criteria
  docs/desktop-browsers.md
Labels: c:browsers, t:correction

#2618 fix: Update last criterion on MFA tools page
  docs/basics/email-security.md
  docs/multi-factor-authentication.md
  docs/os/qubes-overview.md
Labels: c:providers
