Repository privacyguides/privacyguides.org, pull requests merged in 2024-05, with the labels that each got.

#2558 remove leftover brackets
  docs/basics/common-threats.md
Labels: t:correction

#2557 Update Notesnook logo and information
  docs/notebooks.md
  theme/assets/img/notebooks/notesnook.svg
Labels: c:software, t:correction

#2565 Remove mention of LocalMonero in the Knowledge Base
  docs/advanced/payments.md
Labels: c:providers

#2567 Add Flatpak link for Notesnook
  docs/notebooks.md
Labels: c:software, t:correction

#2563 Mention that Mullvad accepts prepaid cards
  docs/vpn.md
Labels: c:providers, t:correction

#2569 Update GitHub releases link for Proton Mail Android
  docs/email.md
Labels: c:providers

#2568 Mention that IVPN accepts prepaid cards
  docs/vpn.md
Labels: c:providers, t:correction

#2582 Fix/shorten links
  docs/calendar.md
  docs/email.md
  docs/vpn.md
Labels: c:providers, t:correction

#2575 Update Tutanota logo
  docs/calendar.md
  docs/email.md
  docs/tools.md
  theme/assets/img/email/tuta-dark.svg
  theme/assets/img/email/tuta.svg
Labels: c:providers, t:correction

#2576 Clean up analytics code
  docs/about/statistics.md
  includes/strings.en.env
  mkdocs.yml
  theme/assets/javascripts/resolution.js
  theme/partials/copyright.html
  theme/partials/javascripts/consent.html
Labels: c:enhancements

#2578 iVerify Basic downgrade info
  docs/basics/multi-factor-authentication.md
  docs/device-integrity.md
  docs/encryption.md
  docs/tools.md
Labels: c:software

#2587 Update information for Ente
  docs/multi-factor-authentication.md
  docs/photo-management.md
  docs/tools.md
Labels: c:providers, t:correction

#2579 Revise the first minimum requirement for Search Engines
  docs/desktop-browsers.md
  docs/os/linux-overview.md
  docs/search-engines.md
Labels: c:providers, t:correction

#2584 Remove archive
  docs/kb-archive.md
  mkdocs.yml
Labels: c:blog

#2595 Update Ente GitHub links
  docs/cloud.md
  docs/multi-factor-authentication.md
  docs/photo-management.md
  docs/productivity.md
Labels: c:software, t:correction

#2583 Replace external links with internal ones where appropriate and fix internal links
  docs/advanced/dns-overview.md
  docs/basics/common-misconceptions.md
  docs/basics/email-security.md
  docs/tools.md
Labels: c:enhancements
