Repository privacyguides/privacyguides.org, pull requests merged in 2024-01, with the labels that each got.

#2363 Update license year
  .github/workflows/crowdin-upload.yml
  .github/workflows/pages.yml
  CITATION.cff
  LICENSE-CODE
  Pipfile
  README.md
  config/mkdocs-common.yml
  config/mkdocs-offline.yml
  config/mkdocs.en.yml
  config/mkdocs.es.yml
  config/mkdocs.fr.yml
  config/mkdocs.he.yml
  config/mkdocs.it.yml
  config/mkdocs.nl.yml
  config/mkdocs.ru.yml
  config/mkdocs.zh-Hant.yml
  netlify.toml
  theme/assets/stylesheets/extra.css
  theme/assets/stylesheets/home.css
  theme/overrides/home.en.html
Labels: t:correction

#2351 Add section on censorship circumvention
  docs/vpn.md
Labels: c:providers

#2353 Skiff Mail added WKD/OpenPGP support
  docs/email.md
Labels: c:providers, t:correction

#2370 Proton VPN Stealth availability
  docs/vpn.md
Labels: c:providers

#2365 Note Proton Calendar's source availability
  docs/calendar.md
Labels: c:providers

#2360 Add NewsFlash as a recommendation under 'News Aggregators'
  docs/news-aggregators.md
  docs/tools.md
  theme/assets/img/news-aggregators/newsflash.png
Labels: c:software

#2374 Remove gfeeds unmaintained
  docs/news-aggregators.md
  docs/tools.md
  theme/assets/img/news-aggregators/gfeeds.svg
Labels: c:software

#2371 Update Stealth Protocol VPN
  docs/vpn.md
Labels: c:providers, t:correction

#2373 Stolen Data Protection in iOS 17.3
  docs/os/ios-overview.md
Labels: c:os

#2380 Fix Reddit RSS syntax
  docs/news-aggregators.md
Labels: t:correction

#2377 Mention other matrix clients exist
  docs/real-time-communication.md
Labels: c:software
