Repository privacyguides/privacyguides.org, pull requests merged in 2024-04, with the labels that each got.

#2472 Stop using Netlify for production hosting
  .editorconfig
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  config/caddy/Caddyfile
  config/caddy/README.md
  config/caddy/common/00-matchers.caddy
  config/caddy/common/30-errors.caddy
  config/caddy/common/30-headers.caddy
  config/caddy/common/50-redirect.caddy
  config/caddy/common/55-redirect-lang.caddy
  config/caddy/common/55-redirect-outdated.caddy
  config/caddy/common/80-canonical.caddy
  config/caddy/production/https.caddy
  config/caddy/production/matrix.caddy
  config/caddy/production/minio.caddy
  config/mkdocs-common.yml
  docs/about/privacy-policy.md
  docs/about/statistics.md
  includes/strings.en.env
  theme/assets/javascripts/resolution.js
  theme/partials/javascripts/consent.html
Labels: c:enhancements

#2471 Update email aliasing links
  docs/basics/account-creation.md
  docs/financial-services.md
  docs/os/ios-overview.md
Labels: t:correction

#2429 Add Peergos in Cloud Storage section
  docs/cloud.md
  docs/tools.md
  theme/assets/img/cloud/peergos.svg
Labels: c:providers

#2481 Bring back feedback buttons
  config/mkdocs-common.yml
  theme/assets/javascripts/feedback.js
  theme/assets/javascripts/resolution.js
  theme/main.html
Labels: c:enhancements

#2480 Update remaining email aliasing links
  docs/email-aliasing.md
  docs/email.md
Labels: t:correction

#2461 Separate browser extensions page
  config/mkdocs-common.yml
  docs/browser-extensions.md
  docs/desktop-browsers.md
  docs/desktop.md
  docs/mobile-browsers.md
  docs/tools.md
  theme/assets/img/cover/browser-extensions.webp
Labels: c:enhancements

#2483 Update links on Frontends page
  docs/frontends.md
Labels: c:software

#2485 Fix Dead/Outdated Links
  docs/basics/account-deletion.md
  docs/desktop-browsers.md
Labels: t:correction

#2486 Make grammar changes on Code of Conduct page
  docs/CODE_OF_CONDUCT.md
  docs/basics/account-deletion.md
Labels: t:correction

#2478 Add VPN comparison table
  docs/vpn.md
Labels: c:providers, c:enhancements

#2499 Add Startpage hidden service address
  docs/search-engines.md
Labels: c:providers, t:correction

#2501 Fix Proton VPN free server number and links
  docs/vpn.md
Labels: c:providers, t:correction

#2503 Update tomb steganography link
  docs/encryption.md
Labels: c:software, t:correction

#2459 Add Proton Pass & password management page updates
  docs/passwords.md
  docs/tools.md
  theme/assets/img/password-management/protonpass.svg
Labels: c:software

#2496 Broaden frontend software criteria
  docs/frontends.md
Labels: c:providers

#2504 Standardize language on VPN Services page
  docs/dns.md
  docs/tools.md
  docs/vpn.md
Labels: t:correction

#2507 Link to mirrors in README
  .github/workflows/build-container.yml
  .github/workflows/build.yml
  .github/workflows/test-build.yml
  .github/workflows/test-lint.yml
  .vscode/settings.json
  docs/about/statistics.md
  docs/cloud.md
  docs/email-aliasing.md
Labels: c:enhancements

#2510 Email: Mention free Proton account deletion
  docs/email.md
Labels: c:providers

#2495 Add Redlib (Reddit frontend)
  docs/frontends.md
  theme/assets/img/frontends/redlib.svg
Labels: c:software

#2512 Edit Proton Mail recommendation card & better wording
  docs/email.md
Labels: c:providers, t:correction

#2517 Add run.sh script to project
  .devcontainer/devcontainer.json
  .devcontainer/team/devcontainer.json
  .github/workflows/build.yml
  .gitignore
  .mailmap
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  mkdocs-production.yml
  mkdocs.yml
  run.sh
  theme/partials/content.html
  theme/partials/source-file.html
Labels: ci:build i18n

#2505 Add search engine comparison table
  docs/search-engines.md
Labels: c:providers

#2467 Common Threats: Supply chain attacks
  .devcontainer/devcontainer.json
  docs/basics/common-misconceptions.md
  docs/basics/common-threats.md
  theme/assets/stylesheets/extra.css
Labels: c:guides

#2521 Fixed typo in common-threats.md
  docs/basics/common-threats.md
Labels: c:guides, t:correction

#2518 Add email service comparison table
  docs/email.md
Labels: c:providers, c:enhancements

#2097 Relicensing: CC BY-SA 4.0
  .github/PULL_REQUEST_TEMPLATE.md
  CITATION.cff
  LICENSE
  README.md
  docs/about/index.md
  docs/about/notices.md
  mkdocs.yml
Labels: m:contributing

#2539 Remove mention of ProtonVPN Linux clients not having 2FA
  docs/vpn.md
Labels: c:providers, t:correction

#2544 Update Web Application for Notesnook in Notebooks section.
  docs/notebooks.md
Labels: c:software, t:correction

#2013 Add LanguageTool
  docs/productivity.md
  docs/tools.md
  theme/assets/img/productivity/languagetool-dark.svg
  theme/assets/img/productivity/languagetool.svg
Labels: c:software

#2546 Fix blog links
  includes/contributors.md
Labels: c:blog

#2545 Append free trial infomation of Ente.io at Photo Management.
  docs/photo-management.md
Labels: c:software, t:correction

#2542 Revise notes on Mull/GeckoView Android
  docs/mobile-browsers.md
Labels: c:browsers, t:correction

#2548 Move paste services criteria and establish language services criteria
  docs/productivity.md
Labels: c:software
