Repository privacyguides/privacyguides.org, pull requests merged in 2024-08, with the labels that each got.

#2675 feat: Add noscript fallback to homepage
  theme/home.html
Labels: c:enhancements

#2674 fix: Update Ente Photos description and remove redundant criterion
  docs/cloud.md
  docs/photo-management.md
Labels: c:providers

#2683 docs: Update our list of volunteers
  .all-contributorsrc
  README.md
  docs/about.md
  docs/about/donate.md
  docs/about/index.md
  docs/mobile-phones.md
  docs/tools.md
  includes/contributors.md
  mkdocs.yml
Labels: m:contributing

#2687 docs: Use style commit type for minor grammar/typo fixes
  docs/meta/commit-messages.md
Labels: t:correction

#2685 ci: Use strict mkdocs builds on PR previews
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
Labels: c:enhancements

#2682 update: Remove mentions of transactional updates and X11 utilities
  docs/desktop.md
  docs/os/linux-overview.md
Labels: c:os

#2585 fix: Remove broken invidious embeds
  docs/basics/multi-factor-authentication.md
  docs/os/linux-overview.md
Labels: t:bug

#2691 update: Mandatory access control explainer
  docs/os/linux-overview.md
Labels: c:os

#2690 update: Remove Wayland section from and add Permission Controls section to Linux Overview
  docs/assets/img/linux/screenshot_permission.png
  docs/desktop.md
  docs/os/linux-overview.md
Labels: c:os

#2693 update: Add Canary Mail iOS download link
  docs/email-clients.md
Labels: t:correction

#2695 update: Mention that you can modify the digits of your Signal username
  docs/real-time-communication.md
Labels: c:software, t:correction

#2689 feat!: Add threat model labels (continues #2605)
  docs/alternative-networks.md
  docs/android/distributions.md
  docs/android/general-apps.md
  docs/browser-extensions.md
  docs/calendar.md
  docs/cloud.md
  docs/cryptocurrency.md
  docs/desktop-browsers.md
  docs/device-integrity.md
  docs/dns.md
  docs/document-collaboration.md
  docs/email-aliasing.md
  docs/encryption.md
  docs/file-sharing.md
  docs/language-tools.md
  docs/mobile-browsers.md
  docs/mobile-phones.md
  docs/multi-factor-authentication.md
  docs/notebooks.md
  docs/passwords.md
  docs/photo-management.md
  docs/real-time-communication.md
  docs/security-keys.md
  docs/tools.md
  docs/tor.md
  docs/vpn.md
Labels: c:enhancements

#2714 update: Remove mention of Matrix clients other than Element
  docs/real-time-communication.md
Labels: c:software

#2708 update!: Data broker removal services
  docs/data-broker-removals.md
  docs/tools.md
  mkdocs.yml
  theme/assets/img/cover/data-broker-removals.webp
  theme/assets/img/data-broker-removals/easyoptouts.svg
  theme/assets/img/data-broker-removals/google.svg
  theme/assets/img/data-broker-removals/optery.svg
Labels: c:providers

#2718 update(blog): Staff announcement
  blog/posts/staff-announcement.md
Labels: ci:build blog

#2717 docs(blog): Re-add profile info to blog authors
  blog/.authors.yml
  blog/archive/2019.md
  blog/archive/2020.md
  blog/archive/2021.md
  blog/archive/2022.md
  blog/author/freddy.md
  blog/author/jonah.md
  blog/author/niek-de-wilde.md
  blog/posts/grapheneos-or-calyxos.md
  blog/posts/i18n-announcement.md
  blog/posts/linux-system-hardening.md
  blog/posts/merch-announcement.md
  blog/posts/move-fast-and-break-things.md
  blog/posts/threads-launch-twitter.md
  blog/posts/virtual-insanity.md
  blog/posts/welcome-to-privacy-guides.md
  docs/android/distributions.md
  docs/android/general-apps.md
  docs/device-integrity.md
  docs/mobile-phones.md
  docs/os/android-overview.md
  theme/main.html
Labels: ci:build blog

#2713 update: Recommend Argon2id when using Bitwarden
  docs/passwords.md
Labels: c:software

#2725 update: Remove DivestOS warning
  docs/android/distributions.md
Labels: c:os

#2734 update: Briefly mention Bitwarden Send and Proton Drive on File Sharing page
  docs/file-sharing.md
  docs/passwords.md
Labels: c:software

#2729 update!: Move Molly from blog post to RTC page
  blog/posts/signal-configuration-and-hardening.md
  docs/real-time-communication.md
  theme/assets/img/messengers/molly.svg
Labels: ci:build blog

#2726 update: Add subscription termination info to Email Aliasing
  docs/email-aliasing.md
  docs/email.md
Labels: c:providers

#2737 update: Thunderbird logo
  docs/email-clients.md
  theme/assets/img/email-clients/thunderbird.svg
Labels: c:software

#2741 update: Note that blocking cookies on Thunderbird may affect email logins
  docs/email-clients.md
Labels: c:software

#2736 update: Replace Proton privacy policy links with more specific ones
  docs/calendar.md
  docs/cloud.md
  docs/email.md
Labels: c:providers
