Repository privacyguides/privacyguides.org, pull requests merged in 2024-07, with the labels that each got.

#2626 iOS Location Services Clarifications
  docs/os/ios-overview.md
Labels: c:os

#2632 update: Add information about Firefox's "privacy-preserving" ad measurement
  docs/desktop-browsers.md
Labels: c:browsers

#2646 fix: Replace iVerify Basic homepage link
  docs/device-integrity.md
Labels: c:guides, t:correction

#2637 fix: Replace links to documentation in Safari card
  docs/desktop-browsers.md
  docs/mobile-browsers.md
Labels: c:browsers, t:correction

#2561 Updated recommended Brave configuration
  docs/mobile-browsers.md
Labels: c:browsers, t:correction

#2641 Update Brave Fingerprint settings
  docs/desktop-browsers.md
Labels: c:browsers, c:software

#2647 Update obsolete Brave info (pkg on macOS)
  docs/desktop-browsers.md
Labels: t:correction

#2653 fix: change Ente Auth logo
  docs/multi-factor-authentication.md
  docs/tools.md
  theme/assets/img/multi-factor-authentication/ente-auth.png
  theme/assets/img/multi-factor-authentication/ente-auth.svg
Labels: c:software, t:correction

#2621 feat: Initial homepage redesign
  docs/index.md
  includes/strings.en.env
  run.sh
  theme/assets/javascripts/discourse-topics.js
  theme/assets/stylesheets/home.css
  theme/home.html
Labels: c:enhancements

#2654 fix: Remove Open Source from Strongbox
  docs/passwords.md
Labels: c:software

#2651 fix: Replace broken Yattee YouTube guide link
  docs/frontends.md
Labels: c:software, t:correction

#2643 update: Update Financial Services and Cryptocurrency pages
  docs/cryptocurrency.md
  docs/financial-services.md
  docs/tools.md
Labels: c:providers

#2620 update!: Split up Android recommendation page into separate pages
  docs/android.md
  docs/android/distributions.md
  docs/android/general-apps.md
  docs/android/index.md
  docs/android/obtaining-apps.md
  docs/device-integrity.md
  docs/mobile-phones.md
  docs/os/android-overview.md
  docs/os/index.md
  docs/os/ios-overview.md
  docs/tools.md
  mkdocs.yml
Labels: c:enhancements

#2606 fix: Improvements on Windows overview
  docs/about/donate.md
  docs/os/index.md
  docs/os/windows/index.md
  includes/abbreviations.en.txt
Labels: t:correction

#2658 fix: Update brave browser settings
  docs/desktop-browsers.md
Labels: t:correction

#2268 Add hardware guide to knowledge base
  docs/basics/common-threats.md
  docs/basics/hardware.md
  docs/os/ios-overview.md
  docs/os/windows/index.md
  includes/abbreviations.en.txt
  mkdocs.yml
Labels: c:hardware

#2669 fix: Move Hardware Guide to Knowledge Base
  mkdocs.yml
Labels: t:correction
