Repository privacyguides/privacyguides.org, pull requests merged in 2024-11, with the labels that each got.

#2782 update: iOS Overview and Safari config after iOS 18
  docs/assets/img/ios/contact-permissions-dark.png
  docs/assets/img/ios/contact-permissions-light.png
  docs/assets/img/ios/photo-permissions-dark.png
  docs/assets/img/ios/photo-permissions-light.png
  docs/assets/img/ios/private-access-dark.png
  docs/assets/img/ios/private-access-light.png
  docs/mobile-browsers.md
  docs/os/ios-overview.md
  docs/tools.md
Labels: c:os

#2796 update: GitHub releases link for Bitwarden
  docs/passwords.md
Labels: c:software

#2798 fix: Replace adguard.com link with adguard-dns.io
  docs/dns.md
Labels: c:providers, t:correction

#2795 update: Thunderbird Mobile's Stable version is now available
  docs/email-clients.md
  docs/encryption.md
  docs/tools.md
  theme/assets/img/email-clients/k9mail.svg
Labels: c:software

#2801 update!: Remove Fluent Reader
  docs/news-aggregators.md
  docs/tools.md
  theme/assets/img/news-aggregators/fluent-reader.svg
Labels: c:software

#2802 update: iOS 18 Browser Recommendations Improvements
  docs/mobile-browsers.md
Labels: c:browsers

#2788 update: Add criteria to VPN Services page and update other sections
  docs/advanced/tor-overview.md
  docs/mobile-browsers.md
  docs/os/android-overview.md
  docs/real-time-communication.md
  docs/vpn.md
  includes/abbreviations.en.txt
Labels: c:providers, t:correction

#2804 style: typo in 'Create Internet Accounts Privately' guide
  docs/about.md
  docs/about/contributors.md
  docs/about/jobs/journalist.md
  docs/basics/account-creation.md
  docs/data-broker-removals.md
  docs/real-time-communication.md
  docs/tools.md
  docs/tor.md
Labels: t:correction

#2800 update: Include disabling search suggestions in browser configs
  docs/desktop-browsers.md
  docs/mobile-browsers.md
Labels: c:browsers

#2805 update: Refine OS Encryption section
  docs/encryption.md
  docs/os/macos-overview.md
  docs/tools.md
Labels: c:software

#2519 update: More detailed Session description
  docs/real-time-communication.md
Labels: c:software

#2809 fix: Correct broken statistics link
  docs/about/statistics.md
  theme/assets/javascripts/feedback.js
Labels: t:bug

#2381 update!: Add Cromite to Mobile Browsers
  docs/browser-extensions.md
  docs/mobile-browsers.md
  docs/search-engines.md
  docs/tools.md
  theme/assets/img/browsers/cromite.svg
Labels: c:browsers

#2808 docs: Update size requirements for company logos
  docs/meta/uploading-images.md
Labels: m:contributing

#2807 docs: Add missing contributors
  .all-contributorsrc
  README.md
  includes/contributors.md
Labels: m:contributing

#2813 update(blog)!: Where are all the Multi-Party Relays?
  blog/.authors.yml
  blog/assets/images/where-are-all-the-mprs/icloud-private-relay.png
  blog/posts/where-are-all-the-mprs.md
Labels: c:blog, ci:build blog

#2815 update: Remove outdated master password info from Proton Pass entry
  docs/passwords.md
Labels: c:software, t:correction

#2816 update: Add Signal Android GitHub releases download link
  docs/real-time-communication.md
Labels: c:software

#2817 update: Privacy Notes section of iOS Overview
  docs/os/ios-overview.md
Labels: c:os, t:correction

#2822 docs: Link to our Bluesky profile
  .github/workflows/publish-pr.yml
  README.md
  blog/.authors.yml
  blog/author/jonah.md
  mkdocs.blog.yml
  mkdocs.yml
Labels: ci:build blog

#2820 update: List of EasyOptOuts unsupported sites
  docs/data-broker-removals.md
Labels: c:providers

#2810 update!: Add local AI chat recommendations
  docs/ai-chat.md
  docs/tools.md
  includes/abbreviations.en.txt
  mkdocs.yml
  theme/assets/img/ai-chat/kobold.png
  theme/assets/img/ai-chat/llamafile.svg
  theme/assets/img/ai-chat/ollama.png
  theme/assets/img/cover/ai-chatbots.webp
Labels: c:software

#2818 update: IzzyOnDroid subsection on Obtaining Android Apps page
  docs/android/obtaining-apps.md
Labels: c:os

#2821 update(blog)!: State of the Web App
  blog/assets/images/pwa-vs-iwa/iwa-diagram.png
  blog/posts/pwa-vs-iwa.md
Labels: c:blog, ci:build blog
