Repository privacyguides/privacyguides.org, pull requests merged in 2024-03, with the labels that each got.

#2419 Convert 6 pages to HTML admonitions
  docs/data-redaction.md
  docs/dns.md
  docs/multi-factor-authentication.md
  docs/tools.md
  docs/tor.md
  docs/vpn.md
Labels: c:enhancements

#2424 Convert 4 pages to HTML admonitions
  docs/frontends.md
  docs/notebooks.md
  docs/passwords.md
  docs/productivity.md
Labels: c:enhancements

#2425 Convert ALL knowledge base pages to HTML admonitions
  docs/advanced/payments.md
  docs/advanced/tor-overview.md
  docs/basics/account-creation.md
  docs/basics/common-misconceptions.md
  docs/basics/common-threats.md
  docs/basics/multi-factor-authentication.md
  docs/basics/passwords-overview.md
  docs/basics/vpn-overview.md
  docs/os/android-overview.md
  docs/os/ios-overview.md
  docs/os/macos-overview.md
  docs/os/qubes-overview.md
Labels: c:enhancements

#2426 NextDNS logging is opt-out, not opt-in.
  docs/dns.md
Labels: c:providers, t:correction

#2422 Update Brave cookies settings and move social media blocking
  docs/desktop-browsers.md
Labels: c:browsers, t:correction

#2369 Include Tor instances link in frontends.md
  docs/frontends.md
  docs/productivity.md
Labels: t:correction

#2428 Update Element organization link
  docs/real-time-communication.md
Labels: c:software, t:correction

#2431 Fix downloads for Miniflux
  docs/news-aggregators.md
Labels: c:software, t:bug

#2432 Update ente card
  docs/multi-factor-authentication.md
  docs/photo-management.md
Labels: c:software, t:correction

#2434 Clarification of NextDNS logging policy
  docs/dns.md
Labels: c:providers, t:correction

#2409 Add Email Aliasing page
  config/mkdocs-offline.yml
  config/mkdocs.en.yml
  config/mkdocs.es.yml
  config/mkdocs.fr.yml
  config/mkdocs.he.yml
  config/mkdocs.it.yml
  config/mkdocs.nl.yml
  config/mkdocs.ru.yml
  config/mkdocs.zh-Hant.yml
  docs/email-aliasing.md
  docs/email.md
  docs/tools.md
  theme/assets/img/cover/email-aliasing.webp
  theme/assets/img/email-aliasing/addy.svg
  theme/assets/img/email-aliasing/simplelogin.svg
  theme/assets/img/email/addy-dark.svg
  theme/assets/img/email/addy.svg
Labels: c:providers

#2438 Randomize DNS table order
  config/mkdocs-common.yml
  docs/dns.md
  theme/assets/javascripts/randomize-element.js
  theme/main.html
Labels: c:enhancements

#2403 Change team member card layout
  docs/about/index.md
Labels: c:enhancements

#2455 Remove Brave's Flatpak footnote
  docs/desktop-browsers.md
Labels: c:software, t:correction

#2330 Reorganize DNS recommendations
  docs/advanced/dns-overview.md
  docs/dns.md
  theme/assets/img/dns/control-d.svg
  theme/assets/img/dns/nextdns.svg
Labels: c:enhancements

#2453 Ente Auth has now desktop apps available for all platforms
  docs/multi-factor-authentication.md
Labels: c:software, t:correction

#2458 Revert "Ente Auth desktop apps on all platforms (#2453)"
  docs/multi-factor-authentication.md
Labels: c:software, t:correction

#2457 Change link to icon on DNS provider table
  docs/dns.md
Labels: c:providers, t:bug

#2462 Use GitHub Actions instead of Netlify for builds
  .github/workflows/build-offline.yml
  .github/workflows/build.yml
  .github/workflows/cleanup.yml
  .github/workflows/deploy.yml
  .github/workflows/download-repo.yml
  .github/workflows/pages.yml
  .github/workflows/publish-mirror.yml
  .github/workflows/publish-pr.yml
  .github/workflows/publish-release.yml
  .github/workflows/upload-crowdin.yml
  .vscode/extensions.json
  README.md
  config/layouts/home.yml
  config/mkdocs-common.yml
  config/mkdocs-offline.yml
  config/mkdocs.en.yml
  config/mkdocs.es.yml
  config/mkdocs.fr.yml
  config/mkdocs.he.yml
  config/mkdocs.it.yml
  config/mkdocs.nl.yml
  config/mkdocs.ru.yml
  config/mkdocs.zh-Hant.yml
  includes/strings.en.env
  includes/strings.en.yml
  netlify.toml
  theme/main.html
Labels: c:enhancements
