Repository privacyguides/privacyguides.org, pull requests merged in 2024-02, with the labels that each got.

#2398 Remove Skiff Mail
  docs/email.md
  docs/tools.md
  theme/assets/img/email/skiff-mail.svg
Labels: c:providers, t:correction

#2376 Convert News Aggregators to HTML admonitions
  docs/news-aggregators.md
Labels: t:bug

#2385 Convert "Email clients" page to HTML admontions
  docs/email-clients.md
Labels: c:providers, t:bug

#2378 Fix broken blacklisting link (html admonition)
  docs/android.md
Labels: t:correction, t:bug

#2389 Convert Cloud storage page to HTML admonitions
  docs/cloud.md
Labels: c:providers

#2390 Convert Financial Services page to HTML admonitions
  docs/financial-services.md
Labels: t:bug

#2391 Convert routers page to HTML admonitions
  docs/router.md
Labels: t:bug

#2392 Convert Desktop browsers page to HTML admonitions
  docs/desktop-browsers.md
Labels: c:browsers, t:bug

#2394 Change link to Nitter instances in News Aggregators page
  docs/news-aggregators.md
Labels: t:correction

#2396 Convert Search Engines page to HTML admonitions
  docs/search-engines.md
Labels: t:correction

#2338 Update Safari settings for iOS 17
  docs/mobile-browsers.md
Labels: c:os, t:correction

#2393 Recommend Fedora Atomic Desktops (rebranded)
  docs/desktop.md
  docs/tools.md
  theme/assets/img/linux-desktop/fedora-silverblue.svg
  theme/assets/img/linux-desktop/fedora.svg
Labels: c:os

#2401 Fix fedora workstation logo
  docs/desktop.md
Labels: c:os, t:bug

#2400 Convert Encryption Software page to HTML admonitions
  docs/encryption.md
Labels: t:bug

#2402 Rebranding 'Immutable Distributions'
  docs/desktop.md
  docs/os/linux-overview.md
Labels: c:os

#2399 Mention video memory clearing on Tails
  docs/desktop.md
Labels: c:os

#2405 Convert Mobile Browsers page to HTML admonitions
  docs/mobile-browsers.md
Labels: c:browsers

#2408 Add Permissions-Policy HTTP header
  netlify.toml
Labels: c:enhancements

#2410 Remove Nitter
  docs/frontends.md
  docs/news-aggregators.md
  docs/tools.md
  theme/assets/img/frontends/nitter.svg
Labels: c:software, t:correction

#2415 Convert Cryptocurrency page to HTML admonitions
  docs/cryptocurrency.md
Labels: c:enhancements

#2414 Remove social media links
  theme/main.html
Labels: t:correction

#2416 Add editor config
  .editorconfig
  .gitignore
  .python-version
  .vscode/extensions.json
  .vscode/settings.json
  Pipfile.lock
Labels: m:contributing
