Repository privacyguides/privacyguides.org, pull requests merged in 2024-10, with the labels that each got.

#2779 update: Remove AMO link from uBOL card
  docs/browser-extensions.md
Labels: c:browsers

#2735 update: Note YouTube's API changes and reorder YT frontends
  docs/frontends.md
Labels: c:software

#2781 update: Add Picocrypt audit
  docs/cloud.md
  docs/encryption.md
Labels: c:software

#2783 update: Remove Play Store link for Syncthing
  docs/file-sharing.md
Labels: c:software, t:correction

#2784 update: Document Android Private Space and preference for it over Shelter
  docs/android/general-apps.md
  docs/os/android-overview.md
Labels: c:software, c:os

#2780 update: Remove Brave's IPFS mentions and add separate iOS configs
  docs/desktop-browsers.md
  docs/mobile-browsers.md
Labels: c:browsers, t:correction

#2778 update: Description of group calls for Element
  docs/real-time-communication.md
Labels: c:software

#2775 feat: Add remaining threat model labels
  docs/android/general-apps.md
  docs/data-redaction.md
  docs/desktop.md
  docs/financial-services.md
  docs/language-tools.md
  docs/office-suites.md
  docs/pastebins.md
  docs/router.md
  docs/search-engines.md
  docs/tools.md
Labels: c:enhancements

#2702 update: macOS Section
  docs/os/macos-overview.md
Labels: c:os, t:correction

#2785 update!: Post three job openings
  blog/posts/job-openings.md
  crowdin.yml
  docs/about/jobs.md
  docs/about/jobs/content-creator.md
  docs/about/jobs/intern-news.md
  docs/about/jobs/journalist.md
Labels: ci:build blog

#2790 build: Disable revision dates on localized site
  .github/dependabot.yml
  .github/workflows/build.yml
  Pipfile.lock
  crowdin.yml
Labels: ci:build i18n, ci:build blog

#2715 update!: Remove iVerify Basic
  docs/device-integrity.md
  docs/tools.md
  theme/assets/img/device-integrity/iverify.webp
Labels: c:software
