Repository privacyguides/privacyguides.org, pull requests merged in 2025-02, with the labels that each got.

#2876 update(blog): Add Em's author bio
  blog/author/em.md
Labels: c:blog, ci:build blog

#2874 update(blog)!: The future of privacy
  blog/assets/images/the-future-of-privacy/cover.webp
  blog/posts/the-future-of-privacy.md
Labels: c:blog, ci:build blog

#2879 update: Fix broken rpm-ostree link
  docs/desktop.md
Labels: c:os, t:correction

#2875 update: Add info to EasyOptOuts listing
  docs/data-broker-removals.md
Labels: c:providers

#2873 update: Add Proton Pass Plus as another way of having SimpleLogin premium
  docs/email-aliasing.md
Labels: c:software

#2867 update: add info about paid Cryptomator apps
  docs/encryption.md
Labels: c:software

#2862 update: add second audit for peergos
  docs/cloud.md
Labels: c:providers

#2854 update: Add links to monerod reference and Tor/VPN pages to Monero nodes section, small markdown tidying in cryptocurrency.md
  docs/cryptocurrency.md
Labels: c:software

#2880 update(blog)!: CryptPad Review
  blog/assets/images/cryptpad-review/cryptpad-calendar.webp
  blog/assets/images/cryptpad-review/cryptpad-code.webp
  blog/assets/images/cryptpad-review/cryptpad-cover.webp
  blog/assets/images/cryptpad-review/cryptpad-creatingfile.webp
  blog/assets/images/cryptpad-review/cryptpad-deletingfiles.webp
  blog/assets/images/cryptpad-review/cryptpad-diagram.webp
  blog/assets/images/cryptpad-review/cryptpad-document.webp
  blog/assets/images/cryptpad-review/cryptpad-filetypes.webp
  blog/assets/images/cryptpad-review/cryptpad-form.webp
  blog/assets/images/cryptpad-review/cryptpad-kanban.webp
  blog/assets/images/cryptpad-review/cryptpad-login.webp
  blog/assets/images/cryptpad-review/cryptpad-markdown.webp
  blog/assets/images/cryptpad-review/cryptpad-presentation.webp
  blog/assets/images/cryptpad-review/cryptpad-profile.webp
  blog/assets/images/cryptpad-review/cryptpad-richtext.webp
  blog/assets/images/cryptpad-review/cryptpad-sheet.webp
  blog/assets/images/cryptpad-review/cryptpad-trackingchanges.webp
  blog/assets/images/cryptpad-review/cryptpad-whiteboard.webp
  blog/posts/cryptpad-review.md
  blog/posts/onion-browser-review.md
Labels: c:blog, ci:build blog

#2881 update: Remove GladIKnow from data broker removal list
  docs/data-broker-removals.md
Labels: c:providers

#2877 update(blog): Minor updates to author bios
  blog/author/dngray.md
  blog/author/freddy.md
Labels: c:blog, ci:build blog

#2868 update: mention anonymous payment methods for SimpleLogin and addy.io
  docs/about.md
  docs/cryptocurrency.md
  docs/data-broker-removals.md
  docs/email-aliasing.md
  docs/mobile-browsers.md
  docs/os/ios-overview.md
Labels: c:providers

#2866 update: Add links to Mullvad and IVPN audits
  docs/vpn.md
Labels: c:providers

#2826 update(blog)!: Biometrics article
  .vscode/ltex.dictionary.en-US.txt
  .vscode/ltex.disabledRules.en-US.txt
  .vscode/ltex.hiddenFalsePositives.en-US.txt
  .vscode/settings.json
  blog/assets/images/biometrics-explained/biometrics.webp
  blog/assets/images/biometrics-explained/capacitve-diagram.webp
  blog/assets/images/biometrics-explained/finger-minutiae.webp
  blog/assets/images/biometrics-explained/kinect-skeleton.webp
  blog/assets/images/biometrics-explained/model-free-gait.webp
  blog/assets/images/biometrics-explained/optical-diagram.webp
  blog/assets/images/biometrics-explained/types-of-fingerprint.webp
  blog/assets/images/biometrics-explained/ultrasonic-diagram.webp
  blog/posts/biometrics-explained.md
  mkdocs.blog.yml
Labels: c:blog, ci:build blog

#2878 update(blog)!: Clearing Your Browsing Data
  blog/.authors.yml
  blog/assets/images/clearing-your-browsing-data/brave1.webp
  blog/assets/images/clearing-your-browsing-data/brave2.webp
  blog/assets/images/clearing-your-browsing-data/brave3.webp
  blog/assets/images/clearing-your-browsing-data/brave4.webp
  blog/assets/images/clearing-your-browsing-data/brave5.webp
  blog/assets/images/clearing-your-browsing-data/brave6.webp
  blog/assets/images/clearing-your-browsing-data/chrome1.webp
  blog/assets/images/clearing-your-browsing-data/chrome2.webp
  blog/assets/images/clearing-your-browsing-data/chrome3.webp
  blog/assets/images/clearing-your-browsing-data/chrome4.webp
  blog/assets/images/clearing-your-browsing-data/dimmis-vart-JPu345g_OYM-unsplash.webp
  blog/assets/images/clearing-your-browsing-data/edge1.webp
  blog/assets/images/clearing-your-browsing-data/edge2.webp
  blog/assets/images/clearing-your-browsing-data/edge3.webp
  blog/assets/images/clearing-your-browsing-data/edge4.webp
  blog/assets/images/clearing-your-browsing-data/edge5.webp
  blog/assets/images/clearing-your-browsing-data/firefox1.webp
  blog/assets/images/clearing-your-browsing-data/firefox2.webp
  blog/assets/images/clearing-your-browsing-data/firefox3.webp
  blog/assets/images/clearing-your-browsing-data/firefox4.webp
  blog/assets/images/clearing-your-browsing-data/firefox5.webp
  blog/assets/images/clearing-your-browsing-data/firefox6.webp
  blog/assets/images/clearing-your-browsing-data/history1.webp
  blog/assets/images/clearing-your-browsing-data/history2.webp
  blog/assets/images/clearing-your-browsing-data/history3.webp
  blog/assets/images/clearing-your-browsing-data/safari.webp
  blog/assets/images/clearing-your-browsing-data/safari_privacy.webp
  blog/assets/images/clearing-your-browsing-data/safariprivacy1.webp
  blog/assets/images/clearing-your-browsing-data/safariprivacy2.webp
  blog/posts/clearing-browsing-data.md
Labels: c:blog, ci:build blog

#2893 update(video)!: 5 Easy Steps to Protect Yourself Online
  videos/posts/5-easy-steps-to-protect-yourself-online.md
Labels: ci:build videos

#2894 update(video): Add video sources
  index-generation.sh
  theme/video-post.html
  videos/posts/5-easy-steps-to-protect-yourself-online.md
  videos/posts/do-you-need-a-vpn.md
  videos/posts/its-time-to-stop-using-sms-heres-why.md
Labels: ci:build videos

#2885 update: ProtonVPN WireGuard support on Linux client
  docs/vpn.md
Labels: c:providers

#2889 update(blog)!: Privacy is Not Dead
  blog/assets/images/privacy-is-not-dead/cover.webp
  blog/posts/privacy-is-not-dead.md
  theme/blog-post.html
  theme/layouts/blog.yml
Labels: c:blog, ci:build blog

#2897 feat(blog): Add old article warning
  theme/blog-post.html
Labels: c:blog, ci:build blog

#2898 update: remove OpenVPN requirement
  docs/vpn.md
Labels: c:providers

#2896 update: Fix Mullvad's 30 day refund policy to 14 days
  docs/vpn.md
Labels: c:providers, t:correction

#2886 update: Tumbleweed logo and SELinux default
  docs/os/linux-overview.md
  theme/assets/img/linux-desktop/opensuse-tumbleweed.svg
Labels: c:os

#2912 fix(blog): Make blog posts explicitly timezone-aware
  blog/posts/activists-guide-securing-your-smartphone.md
  blog/posts/bad-faith-arguments.md
  blog/posts/biometrics-explained.md
  blog/posts/choosing-the-right-messenger.md
  blog/posts/clearing-browsing-data.md
  blog/posts/cryptpad-review.md
  blog/posts/delisting-startpage.md
  blog/posts/delisting-wire.md
  blog/posts/easyoptouts-review.md
  blog/posts/firefox-privacy-2021-update.md
  blog/posts/firefox-privacy.md
  blog/posts/grapheneos-or-calyxos.md
  blog/posts/hide-nothing.md
  blog/posts/i18n-announcement.md
  blog/posts/installing-and-using-tails.md
  blog/posts/integrating-metadata-removal.md
  blog/posts/ios-configuration-guide.md
  blog/posts/job-openings.md
  blog/posts/linux-application-sandboxing.md
  blog/posts/linux-system-hardening.md
  blog/posts/macos-ventura-privacy-security-updates.md
  blog/posts/merch-announcement.md
  blog/posts/move-fast-and-break-things.md
  blog/posts/mozilla-disappoints-us-yet-again-2.md
  blog/posts/onion-browser-review.md
  blog/posts/privacy-guides-hires-three-staff-members.md
  blog/posts/privacy-guides-partners-with-magic-grants-501-c-3.md
  blog/posts/privacy-is-not-dead.md
  blog/posts/proton-wallet-review.md
  blog/posts/pwa-vs-iwa.md
  blog/posts/relisting-startpage.md
  blog/posts/restrict-act.md
  blog/posts/secure-data-erasure.md
  blog/posts/security-privacy-anonymity.md
  blog/posts/signal-configuration-and-hardening.md
  blog/posts/signal-number-registration-update.md
  blog/posts/staff-announcement.md
  blog/posts/the-future-of-privacy.md
  blog/posts/the-trouble-with-vpn-and-privacy-review-sites.md
  blog/posts/threads-launch-twitter.md
  blog/posts/virtual-insanity.md
  blog/posts/warning-about-signal-proxies.md
  blog/posts/welcome-to-privacy-guides.md
  blog/posts/weve-joined-the-open-collective-foundation.md
  blog/posts/where-are-all-the-mprs.md
  blog/posts/why-i-run-a-tor-relay.md
  theme/blog-post.html
Labels: c:blog, ci:build blog

#2905 update: Add macOS download link for Bitwarden
  docs/about.md
  docs/passwords.md
Labels: c:software

#2906 update: Replace "discreet merchant" feature with "private spend mode" for privacy.com
  docs/financial-services.md
Labels: c:providers

#2909 update: Correct LanguageTool's data processing note
  docs/language-tools.md
Labels: t:correction
