Repository privacyguides/privacyguides.org, pull requests merged in 2025-03, with the labels that each got.

#2903 update: New features in Brave Browser Android and iOS
  docs/mobile-browsers.md
Labels: c:browsers

#2913 update(video)!: Anonymity for Everyone: Why You Need Tor
  videos/posts/why-you-need-tor.md
Labels: ci:build videos

#2916 update: Remove references to deprecated DNT
  docs/email.md
  docs/vpn.md
Labels: t:correction

#2914 docs!: Update privacy policy
  .vscode/ltex.dictionary.en-US.txt
  .vscode/ltex.disabledRules.en-US.txt
  .vscode/ltex.hiddenFalsePositives.en-US.txt
  .vscode/settings.json
  docs/about/privacy-policy.md
  docs/privacy.md
  docs/tor.md
  includes/strings.en.env
  mkdocs.blog.yml
  mkdocs.net.yml
  mkdocs.videos.yml
  mkdocs.yml
  theme/partials/copyright.html
Labels: ci:build blog, ci:build videos

#2928 update(blog)!: How to Reset Your YubiKey and Create a Backup
  .vscode/ltex.dictionary.en-US.txt
  Pipfile
  Pipfile.lock
  blog/assets/images/yubikey-reset-and-backup/cover.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-1-download.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-10-reset-fido2.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-11-reset-fido2close.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-12-reset-piv.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-13-reset-cli.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-14-config-certificates.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-15-config-certificatespin.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-16-config-certificatespuk.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-17-config-certificateskey.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-18-config-otp.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-19-config-otpfields.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-2-yubicoapp.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-20-config-otpfieldsfilled.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-21-config-otpfile.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-22-config-register.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-23-config-registersuccess.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-24-config-tryitout.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-25-config-challenge.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-26-config-challengepopup.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-27-config-challengespare.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-28-config-spareconfigured.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-29-config-oathtotp.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-3-keysplugged.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-30-config-passkeys.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-31-config-passkeyspin.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-32-deleteslot.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-33-deleteslotpopup.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-34-config-static.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-35-config-statickeyboards.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-36-config-staticspare.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-37-config-hotp.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-38-config-oathhotppopup.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-39-config-pgppins.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-4-keyspluggedspare.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-40-config-pgpgeneratekey.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-41-config-pgppassphrase.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-42-config-pgpaddkeys.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-43-config-pgp3subkeys.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-44-config-pgpimportsubkeys.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-45-config-pgpadminpin.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-5-slots.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-6-deletecredential.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-7-deletepopup.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-8-slotsempty.webp
  blog/assets/images/yubikey-reset-and-backup/yubikey-9-reset-oath.webp
  blog/posts/yubikey-reset-and-backup.md
  mkdocs.blog.yml
  mkdocs.videos.yml
  mkdocs.yml
Labels: c:blog, ci:build blog

#2935 update: Reword introduction to Language Tools page for consistency
  docs/language-tools.md
Labels: c:software, t:correction

#2911 update(blog)!: Toward a Passwordless Future
  .vscode/ltex.dictionary.en-US.txt
  .vscode/ltex.hiddenFalsePositives.en-US.txt
  blog/assets/images/toward-a-passwordless-future/cover.webp
  blog/assets/images/toward-a-passwordless-future/ctss.webp
  blog/posts/toward-a-passwordless-future.md
Labels: c:blog, ci:build blog

#2887 update!: Add section for Health and Wellness apps
  docs/android/obtaining-apps.md
  docs/assets/img/health-and-wellness/apple-health.png
  docs/assets/img/health-and-wellness/commonhealth.png
  docs/assets/img/health-and-wellness/drip.png
  docs/assets/img/health-and-wellness/euki.svg
  docs/assets/img/health-and-wellness/gadgetbridge.svg
  docs/health-and-wellness.md
  docs/tools.md
  mkdocs.yml
  theme/assets/img/cover/health-cover.webp
Labels: c:software

#2827 update!: Add map/navigation recommendations
  docs/maps.md
  docs/tools.md
  mkdocs.yml
  theme/assets/img/cover/maps.webp
  theme/assets/img/maps/organic-maps.svg
  theme/assets/img/maps/osmand.svg
Labels: c:software

#2219 update!: Add Paaster as a Pastebin recommendation
  docs/pastebins.md
  docs/tools.md
  theme/assets/img/pastebins/paaster.svg
Labels: c:software

#2927 feat!: Add list of monthly/annual members to website
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  .github/workflows/publish-release.yml
  .github/workflows/update-discussions.yml
  .gitignore
  docs/about/donate.md
  generate-members.py
  generate-topics.sh
  mkdocs.yml
  theme/assets/img/donors/deleteme.webp
  theme/assets/img/donors/power-up-privacy.webp
  theme/assets/stylesheets/extra.css
  theme/main.html
  theme/partials/donate.html
  theme/partials/header.html
Labels: c:enhancements

#2942 style: OPNsense logo
  theme/assets/img/router/opnsense.svg
Labels: c:os

#2946 style: Replace old Molly logo
  theme/assets/img/messengers/molly.svg
Labels: c:software

#2945 update: Country count for Mullvad servers
  docs/tools.md
  docs/vpn.md
Labels: c:providers

#2918 feat: Surface more videos across the website
  docs/advanced/communication-network-types.md
  docs/advanced/tor-overview.md
  docs/basics/vpn-overview.md
  docs/basics/why-privacy-matters.md
  docs/index.md
  docs/real-time-communication.md
  docs/tor.md
Labels: c:enhancements

#2904 update!: Remove Strongbox
  docs/passwords.md
  docs/tools.md
  theme/assets/img/password-management/strongbox.svg
Labels: c:software

#2955 style(blog): Fix typo in The Privacy of Others article
  blog/posts/the-privacy-of-others.md
Labels: c:blog, t:correction, ci:build blog

#2956 style(video): Video page metadata changes
  mkdocs.videos.yml
  theme/video-post.html
  videos/index.md
Labels: ci:build videos

#2971 update(blog)!: Privacy Means Safety
  blog/assets/images/privacy-means-safety/privacy-means-safety-cover.webp
  blog/posts/privacy-means-safety.md
  blog/posts/the-future-of-privacy.md
  blog/posts/the-privacy-of-others.md
Labels: c:blog, ci:build blog

#2983 update(blog)!: Interview with Micah Lee
  .vscode/ltex.dictionary.en-US.txt
  blog/assets/images/interview-with-micah-lee/micah-lee-cover.webp
  blog/assets/images/interview-with-micah-lee/social-preview-cover.webp
  blog/posts/interview-with-micah-lee.md
  theme/layouts/blog.yml
Labels: c:blog, ci:build blog
