Repository privacyguides/privacyguides.org, pull requests merged in 2025-04, with the labels that each got.

#2989 update(blog)!: [April 1] The Dangers of E2EE
  blog/.authors.yml
  blog/assets/images/the-dangers-of-end-to-end-encryption/cover.webp
  blog/assets/images/the-dangers-of-end-to-end-encryption/fire.svg
  blog/posts/the-dangers-of-end-to-end-encryption.md
  theme/layouts/blog.yml
Labels: c:blog, ci:build blog

#2998 update(blog)!: Encryption is Not a Crime
  blog/assets/images/encryption-is-not-a-crime/encryption-is-not-a-crime-cover.webp
  blog/posts/encryption-is-not-a-crime.md
  blog/posts/the-dangers-of-end-to-end-encryption.md
Labels: c:blog, ci:build blog

#2976 style: Fix sentence in VPN overview
  docs/basics/vpn-overview.md
Labels: c:providers, t:correction

#2962 style: Apply Wikipedia's style of capitalization
  docs/dns.md
  docs/email-aliasing.md
  docs/health-and-wellness.md
  docs/passwords.md
  docs/tools.md
Labels: t:correction

#2963 update: Move custom domain support to best-case criteria for email services
  docs/email.md
Labels: c:providers

#2968 update: Remove "sanitize on close" note for Brave
  docs/desktop-browsers.md
Labels: c:browsers

#2984 update: Change Ente Photos free plan to 10 GB
  docs/photo-management.md
Labels: c:providers

#2997 update: Replace dead link with archived link in hide-nothing.md
  blog/posts/hide-nothing.md
Labels: c:blog, t:correction, ci:build blog

#2961 update!: Add Secureblue
  docs/desktop.md
  docs/tools.md
  theme/assets/img/linux-desktop/secureblue.svg
Labels: c:os

#2974 style: Move AI terms from glossary to recommendation page
  docs/ai-chat.md
  docs/basics/email-security.md
  docs/email.md
  docs/tools.md
  includes/abbreviations.en.txt
  theme/assets/img/ai-chat/llamafile.png
  theme/assets/img/ai-chat/llamafile.svg
Labels: c:software

#2999 update!: Remove Canary Mail
  docs/email-clients.md
  docs/encryption.md
  docs/tools.md
  theme/assets/img/email-clients/canarymail.svg
Labels: c:software

#3004 style: Correct YouTube link to Adam Šamalik's Fedora Silverblue talk
  docs/os/linux-overview.md
Labels: c:os, t:correction

#3003 update: Replace links to Organic Maps GitHub repo with Forgejo links
  docs/maps.md
Labels: c:software

#2996 style: Update Paaster logo
  theme/assets/img/pastebins/paaster.svg
Labels: c:software

#3002 update(blog): Note Signal censorship circumvention settings
  blog/posts/signal-configuration-and-hardening.md
Labels: c:blog, ci:build blog

#3000 update: Note location of Proton VPN Android telemetry
  docs/vpn.md
Labels: c:providers

#2988 style: Update Ente Photos logo
  docs/photo-management.md
  docs/tools.md
  theme/assets/img/photo-management/ente-dark.svg
  theme/assets/img/photo-management/ente.svg
Labels: c:providers

#3008 style: Make commands in macOS page more consistent
  docs/os/macos-overview.md
Labels: c:os

#3001 docs: Guideline for PR comments & reviews
  docs/meta/pr-comments.md
  mkdocs.yml
  theme/assets/img/meta/pr-avoid-general-comments.png
  theme/assets/img/meta/pr-threaded-comment.png
Labels: m:contributing

#2975 style: Reformat parts of DNS table and footnotes
  docs/dns.md
Labels: c:providers, t:correction

#2973 style: Reorganize and tweak email-related pages
  docs/basics/account-creation.md
  docs/basics/email-security.md
  docs/email-aliasing.md
  docs/email-clients.md
  docs/email.md
  docs/os/android-overview.md
  includes/abbreviations.en.txt
Labels: c:providers

#3006 update: Recommend both Fedora desktops equally
  .vscode/ltex.dictionary.en-US.txt
  docs/desktop.md
  docs/tools.md
Labels: c:os

#2960 update(blog)!: Privacy Pass: The New Protocol for Private Authentication
  blog/assets/images/privacy-pass/blind-signatures.webp
  blog/assets/images/privacy-pass/cover.webp
  blog/assets/images/privacy-pass/google-vpn.webp
  blog/assets/images/privacy-pass/private-access-tokens.webp
  blog/posts/privacy-pass.md
Labels: c:blog, ci:build blog

#3015 update(video): Add sources to latest video
  blog/.authors.yml
  videos/.authors.yml
  videos/posts/is-privacy-dead.md
Labels: ci:build blog, ci:build videos

#3020 update(blog)!: In Praise of Tor: Why You Should Support and Use Tor
  blog/assets/images/in-praise-of-tor/tor-cover.webp
  blog/assets/images/in-praise-of-tor/tor-darkweb.webp
  blog/assets/images/in-praise-of-tor/tor-diagram.webp
  blog/assets/images/in-praise-of-tor/tor-privacyguides.webp
  blog/assets/images/in-praise-of-tor/tor-safestsetting.webp
  blog/assets/images/in-praise-of-tor/tor-torbrowser.webp
  blog/assets/images/in-praise-of-tor/tor-torcircuit.webp
  blog/posts/in-praise-of-tor.md
Labels: c:blog, ci:build blog
